import { serve } from 'https://deno.land/std@0.177.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.3';
import { SECURITY_HEADERS } from '../_shared/securityHeaders.ts';

const corsHeaders = {
  'Access-Control-Allow-Origin': Deno.env.get('APP_ORIGIN') ?? 'https://cashpilot.tech',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  ...SECURITY_HEADERS,
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Verify JWT
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      return new Response(JSON.stringify({ error: 'Missing Authorization header' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const token = authHeader.replace('Bearer ', '');
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser(token);
    if (authError || !user) {
      return new Response(JSON.stringify({ error: 'Invalid or expired token' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const { company_id, accountant_email, accountant_name, permissions } = await req.json();

    // Validate required fields
    if (!company_id || !accountant_email) {
      return new Response(JSON.stringify({ error: 'Missing required fields: company_id, accountant_email' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Verify the user owns this company
    const { data: company, error: companyError } = await supabase
      .from('company')
      .select('id, name')
      .eq('id', company_id)
      .eq('user_id', user.id)
      .single();

    if (companyError || !company) {
      return new Response(JSON.stringify({ error: 'Company not found or access denied' }), {
        status: 403,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Check for existing pending invitation to the same email for this company
    const { data: existing } = await supabase
      .from('accountant_invitations')
      .select('id')
      .eq('company_id', company_id)
      .eq('accountant_email', accountant_email.toLowerCase().trim())
      .eq('status', 'pending')
      .maybeSingle();

    if (existing) {
      return new Response(JSON.stringify({ error: 'An invitation is already pending for this email' }), {
        status: 409,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Default permissions
    const defaultPermissions = {
      view_invoices: true,
      view_expenses: true,
      view_accounting: true,
      view_reports: true,
      export_fec: true,
      export_data: true,
    };

    const finalPermissions = permissions ? { ...defaultPermissions, ...permissions } : defaultPermissions;

    // Insert the invitation (token is auto-generated by DB default)
    const { data: invitation, error: insertError } = await supabase
      .from('accountant_invitations')
      .insert({
        user_id: user.id,
        company_id,
        accountant_email: accountant_email.toLowerCase().trim(),
        accountant_name: accountant_name || null,
        permissions: finalPermissions,
      })
      .select()
      .single();

    if (insertError) {
      throw insertError;
    }

    // Send email notification (via send-email edge function)
    const appUrl = Deno.env.get('APP_URL') ?? 'https://cashpilot.tech';
    const inviteUrl = `${appUrl}/accountant/accept?token=${invitation.token}`;

    try {
      await supabase.functions.invoke('send-email', {
        body: {
          to: accountant_email,
          subject: `CashPilot - Invitation au portail comptable de ${company.name}`,
          html: `
            <div style="font-family: system-ui, sans-serif; max-width: 600px; margin: 0 auto;">
              <h2>Invitation au Portail Comptable</h2>
              <p>Bonjour${accountant_name ? ` ${accountant_name}` : ''},</p>
              <p>Vous avez été invité(e) à accéder aux données comptables de <strong>${company.name}</strong> sur CashPilot.</p>
              <p>
                <a href="${inviteUrl}" style="display: inline-block; padding: 12px 24px; background: #6366f1; color: #fff; text-decoration: none; border-radius: 8px;">
                  Accepter l'invitation
                </a>
              </p>
              <p style="color: #666; font-size: 14px;">Ce lien expire dans 30 jours.</p>
              <p style="color: #666; font-size: 14px;">Si vous n'avez pas de compte CashPilot, vous devrez en créer un avec cette adresse email.</p>
            </div>
          `,
          userId: user.id,
        },
        headers: {
          Authorization: authHeader,
        },
      });
    } catch (emailError) {
      // Email sending is best-effort; the invitation is still created
      console.warn('Failed to send invitation email:', emailError);
    }

    // Log to audit
    await supabase.from('audit_log').insert({
      user_id: user.id,
      action: 'accountant_invited',
      details: {
        resource: 'accountant_invitation',
        new_data: {
          invitation_id: invitation.id,
          company_id,
          accountant_email,
          accountant_name,
        },
      },
    });

    return new Response(JSON.stringify({ success: true, invitation }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (error) {
    console.error('Accountant invite error:', error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
