import html2pdf from 'html2pdf.js';
import html2canvas from 'html2canvas';

/**
 * Capture chart/element as image
 */
const captureElementAsImage = async (elementId) => {
  const element = document.getElementById(elementId);
  if (!element) return null;

  try {
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#111827' // gray-900
    });
    return canvas.toDataURL('image/png');
  } catch (error) {
    console.error('Failed to capture element:', error);
    return null;
  }
};

/**
 * Export Analytics Dashboard to PDF
 */
export const exportAnalyticsPDF = async (data, companyInfo) => {
  // Capture charts as images
  const revenueChartImg = await captureElementAsImage('revenue-chart');
  const expensesChartImg = await captureElementAsImage('expenses-chart');
  const clientsChartImg = await captureElementAsImage('clients-chart');

  const content = `
    <div style="font-family: Arial, sans-serif; max-width: 1000px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, #8b5cf6 0%, #a78bfa 100%); color: white; padding: 30px; border-radius: 8px; margin-bottom: 30px;">
        <h1 style="margin: 0 0 10px 0; font-size: 32px;">ANALYTICS DASHBOARD</h1>
        <p style="margin: 0; font-size: 16px; opacity: 0.9;">${companyInfo?.name || 'Your Company'}</p>
        <p style="margin: 5px 0 0 0; font-size: 14px; opacity: 0.8;">${new Date().toLocaleDateString('fr-FR')}</p>
      </div>

      <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 30px;">
        <div style="background: #1f2937; padding: 20px; border-radius: 8px; border: 1px solid #374151;">
          <p style="margin: 0; color: #9ca3af; font-size: 12px; text-transform: uppercase;">Total Revenue</p>
          <p style="margin: 10px 0 0 0; color: #22c55e; font-size: 28px; font-weight: bold;">${data.totalRevenue?.toFixed(2) || '0.00'} €</p>
        </div>
        <div style="background: #1f2937; padding: 20px; border-radius: 8px; border: 1px solid #374151;">
          <p style="margin: 0; color: #9ca3af; font-size: 12px; text-transform: uppercase;">Total Expenses</p>
          <p style="margin: 10px 0 0 0; color: #ef4444; font-size: 28px; font-weight: bold;">${data.totalExpenses?.toFixed(2) || '0.00'} €</p>
        </div>
        <div style="background: #1f2937; padding: 20px; border-radius: 8px; border: 1px solid #374151;">
          <p style="margin: 0; color: #9ca3af; font-size: 12px; text-transform: uppercase;">Net Profit</p>
          <p style="margin: 10px 0 0 0; color: ${(data.totalRevenue - data.totalExpenses) >= 0 ? '#22c55e' : '#ef4444'}; font-size: 28px; font-weight: bold;">${((data.totalRevenue || 0) - (data.totalExpenses || 0)).toFixed(2)} €</p>
        </div>
      </div>

      ${revenueChartImg ? `
        <div style="margin-bottom: 30px;">
          <h2 style="color: #f3f4f6; margin-bottom: 15px; font-size: 20px;">Revenue Trends</h2>
          <img src="${revenueChartImg}" style="width: 100%; border-radius: 8px; border: 1px solid #374151;" />
        </div>
      ` : ''}

      ${expensesChartImg ? `
        <div style="margin-bottom: 30px;">
          <h2 style="color: #f3f4f6; margin-bottom: 15px; font-size: 20px;">Expenses Analysis</h2>
          <img src="${expensesChartImg}" style="width: 100%; border-radius: 8px; border: 1px solid #374151;" />
        </div>
      ` : ''}

      ${clientsChartImg ? `
        <div style="margin-bottom: 30px;">
          <h2 style="color: #f3f4f6; margin-bottom: 15px; font-size: 20px;">Revenue by Client</h2>
          <img src="${clientsChartImg}" style="width: 100%; border-radius: 8px; border: 1px solid #374151;" />
        </div>
      ` : ''}

      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #374151; text-align: center; color: #6b7280; font-size: 12px;">
        <p style="margin: 0;">Analytics Report generated by CashPilot - ${new Date().toLocaleString('fr-FR')}</p>
      </div>
    </div>
  `;

  const tempDiv = document.createElement('div');
  tempDiv.innerHTML = content;
  document.body.appendChild(tempDiv);

  const options = {
    margin: 10,
    filename: `Analytics_Report_${new Date().toISOString().split('T')[0]}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
  };

  try {
    await html2pdf().set(options).from(tempDiv).save();
    document.body.removeChild(tempDiv);
    return true;
  } catch (error) {
    document.body.removeChild(tempDiv);
    console.error('PDF export failed:', error);
    throw new Error('Failed to export PDF');
  }
};

/**
 * Export Supplier Report to PDF
 */
export const exportSupplierReportPDF = async (reportData, companyInfo) => {
  const content = `
    <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, #0ea5e9 0%, #38bdf8 100%); color: white; padding: 30px; border-radius: 8px; margin-bottom: 30px;">
        <h1 style="margin: 0 0 10px 0; font-size: 32px;">SUPPLIER REPORT</h1>
        <p style="margin: 0; font-size: 16px; opacity: 0.9;">${companyInfo?.name || 'Your Company'}</p>
        <p style="margin: 5px 0 0 0; font-size: 14px; opacity: 0.8;">${new Date().toLocaleDateString('fr-FR')}</p>
      </div>

      <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 30px;">
        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; border-left: 4px solid #0ea5e9;">
          <p style="margin: 0; color: #075985; font-size: 12px; text-transform: uppercase; font-weight: 600;">Total Spent</p>
          <p style="margin: 10px 0 0 0; color: #0c4a6e; font-size: 24px; font-weight: bold;">${reportData.totalSpent?.toFixed(2) || '0.00'} €</p>
        </div>
        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; border-left: 4px solid #3b82f6;">
          <p style="margin: 0; color: #075985; font-size: 12px; text-transform: uppercase; font-weight: 600;">Total Orders</p>
          <p style="margin: 10px 0 0 0; color: #0c4a6e; font-size: 24px; font-weight: bold;">${reportData.ordersCount || 0}</p>
        </div>
        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; border-left: 4px solid #22c55e;">
          <p style="margin: 0; color: #075985; font-size: 12px; text-transform: uppercase; font-weight: 600;">On-Time Delivery</p>
          <p style="margin: 10px 0 0 0; color: #0c4a6e; font-size: 24px; font-weight: bold;">${reportData.onTimeRate || '0'}%</p>
        </div>
      </div>

      ${reportData.topSuppliers?.length > 0 ? `
        <div style="margin-bottom: 30px;">
          <h2 style="color: #1e3a8a; margin-bottom: 15px; font-size: 20px; border-bottom: 2px solid #0ea5e9; padding-bottom: 10px;">Top Suppliers</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <thead>
              <tr style="background: #f3f4f6;">
                <th style="padding: 12px; text-align: left; border-bottom: 2px solid #0ea5e9; font-weight: 600;">Supplier</th>
                <th style="padding: 12px; text-align: right; border-bottom: 2px solid #0ea5e9; font-weight: 600;">Total Spent</th>
                <th style="padding: 12px; text-align: center; border-bottom: 2px solid #0ea5e9; font-weight: 600;">Orders</th>
              </tr>
            </thead>
            <tbody>
              ${reportData.topSuppliers.map(supplier => `
                <tr style="border-bottom: 1px solid #e5e7eb;">
                  <td style="padding: 10px;">${supplier.name || 'N/A'}</td>
                  <td style="padding: 10px; text-align: right; font-weight: 600;">${supplier.totalSpent?.toFixed(2) || '0.00'} €</td>
                  <td style="padding: 10px; text-align: center;">${supplier.ordersCount || 0}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>
      ` : ''}

      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; color: #6b7280; font-size: 12px;">
        <p style="margin: 0;">Supplier Report generated by CashPilot - ${new Date().toLocaleString('fr-FR')}</p>
      </div>
    </div>
  `;

  const tempDiv = document.createElement('div');
  tempDiv.innerHTML = content;
  document.body.appendChild(tempDiv);

  const options = {
    margin: 10,
    filename: `Supplier_Report_${new Date().toISOString().split('T')[0]}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
  };

  try {
    await html2pdf().set(options).from(tempDiv).save();
    document.body.removeChild(tempDiv);
    return true;
  } catch (error) {
    document.body.removeChild(tempDiv);
    console.error('PDF export failed:', error);
    throw new Error('Failed to export PDF');
  }
};

// ========== HTML EXPORT FUNCTIONS ==========

const downloadHTML = (html, filename) => {
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

const generateStandaloneHTML = (title, content) => {
  return `<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body { margin: 0; padding: 20px; background: #0f172a; color: #f1f5f9; font-family: Arial, sans-serif; }
    @media print { body { background: white; color: black; } }
  </style>
</head>
<body>
  ${content}
</body>
</html>`;
};

/**
 * Export Analytics to HTML
 */
export const exportAnalyticsHTML = async (data, companyInfo) => {
  // Note: HTML export won't include chart images, just data tables
  const content = `
    <div style="font-family: Arial, sans-serif; max-width: 1000px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, #8b5cf6 0%, #a78bfa 100%); color: white; padding: 30px; border-radius: 8px; margin-bottom: 30px;">
        <h1 style="margin: 0 0 10px 0;">ANALYTICS DASHBOARD</h1>
        <p style="margin: 0;">${companyInfo?.name || 'Your Company'} - ${new Date().toLocaleDateString('fr-FR')}</p>
      </div>
      <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px;">
        <div style="background: #1f2937; padding: 20px; border-radius: 8px;">
          <p style="color: #9ca3af; font-size: 12px;">TOTAL REVENUE</p>
          <p style="color: #22c55e; font-size: 28px; font-weight: bold;">${data.totalRevenue?.toFixed(2) || '0.00'} €</p>
        </div>
        <div style="background: #1f2937; padding: 20px; border-radius: 8px;">
          <p style="color: #9ca3af; font-size: 12px;">TOTAL EXPENSES</p>
          <p style="color: #ef4444; font-size: 28px; font-weight: bold;">${data.totalExpenses?.toFixed(2) || '0.00'} €</p>
        </div>
        <div style="background: #1f2937; padding: 20px; border-radius: 8px;">
          <p style="color: #9ca3af; font-size: 12px;">NET PROFIT</p>
          <p style="color: ${(data.totalRevenue - data.totalExpenses) >= 0 ? '#22c55e' : '#ef4444'}; font-size: 28px; font-weight: bold;">${((data.totalRevenue || 0) - (data.totalExpenses || 0)).toFixed(2)} €</p>
        </div>
      </div>
    </div>
  `;

  const html = generateStandaloneHTML('Analytics Dashboard', content);
  downloadHTML(html, `Analytics_${new Date().toISOString().split('T')[0]}`);
};

/**
 * Export Supplier Report to HTML
 */
export const exportSupplierReportHTML = (reportData, companyInfo) => {
  const content = `
    <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, #0ea5e9 0%, #38bdf8 100%); color: white; padding: 30px; border-radius: 8px; margin-bottom: 30px;">
        <h1>SUPPLIER REPORT</h1>
        <p>${companyInfo?.name || 'Your Company'} - ${new Date().toLocaleDateString('fr-FR')}</p>
      </div>
      <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 30px;">
        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; color: #0c4a6e;">
          <p style="font-size: 12px; font-weight: 600;">TOTAL SPENT</p>
          <p style="font-size: 24px; font-weight: bold;">${reportData.totalSpent?.toFixed(2) || '0.00'} €</p>
        </div>
        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; color: #0c4a6e;">
          <p style="font-size: 12px; font-weight: 600;">TOTAL ORDERS</p>
          <p style="font-size: 24px; font-weight: bold;">${reportData.ordersCount || 0}</p>
        </div>
        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; color: #0c4a6e;">
          <p style="font-size: 12px; font-weight: 600;">ON-TIME DELIVERY</p>
          <p style="font-size: 24px; font-weight: bold;">${reportData.onTimeRate || '0'}%</p>
        </div>
      </div>
      ${reportData.topSuppliers?.length > 0 ? `
        <h2 style="color: #1e3a8a;">Top Suppliers</h2>
        <table style="width: 100%; border-collapse: collapse;">
          <thead>
            <tr style="background: #f3f4f6; color: #111827;">
              <th style="padding: 12px; text-align: left;">Supplier</th>
              <th style="padding: 12px; text-align: right;">Total Spent</th>
              <th style="padding: 12px; text-align: center;">Orders</th>
            </tr>
          </thead>
          <tbody>
            ${reportData.topSuppliers.map(supplier => `
              <tr style="border-bottom: 1px solid #e5e7eb;">
                <td style="padding: 10px; color: #f1f5f9;">${supplier.name || 'N/A'}</td>
                <td style="padding: 10px; text-align: right; color: #f1f5f9;">${supplier.totalSpent?.toFixed(2) || '0.00'} €</td>
                <td style="padding: 10px; text-align: center; color: #f1f5f9;">${supplier.ordersCount || 0}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      ` : ''}
    </div>
  `;

  const html = generateStandaloneHTML('Supplier Report', content);
  downloadHTML(html, `Supplier_Report_${new Date().toISOString().split('T')[0]}`);
};

/**
 * Export Dashboard to PDF
 */
export const exportDashboardPDF = async (data, companyInfo) => {
  // Capture charts as images
  const revenueChartImg = await captureElementAsImage('dashboard-revenue-chart');
  const clientChartImg = await captureElementAsImage('dashboard-client-chart');

  const { metrics, recentInvoices, recentTimesheets } = data;

  const content = `
    <div style="font-family: Arial, sans-serif; max-width: 1000px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, #f97316 0%, #fb923c 100%); color: white; padding: 30px; border-radius: 8px; margin-bottom: 30px;">
        <h1 style="margin: 0 0 10px 0; font-size: 32px;">DASHBOARD REPORT</h1>
        <p style="margin: 0; font-size: 16px; opacity: 0.9;">${companyInfo?.name || 'Your Company'}</p>
        <p style="margin: 5px 0 0 0; font-size: 14px; opacity: 0.8;">${new Date().toLocaleDateString('fr-FR')}</p>
      </div>

      <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 30px;">
        <div style="background: #1f2937; padding: 20px; border-radius: 8px; border: 1px solid #374151;">
          <p style="margin: 0; color: #9ca3af; font-size: 12px; text-transform: uppercase;">Total Revenue</p>
          <p style="margin: 10px 0 0 0; color: #f97316; font-size: 28px; font-weight: bold;">${metrics?.revenue?.toFixed(2) || '0.00'} €</p>
        </div>
        <div style="background: #1f2937; padding: 20px; border-radius: 8px; border: 1px solid #374151;">
          <p style="margin: 0; color: #9ca3af; font-size: 12px; text-transform: uppercase;">Profit Margin</p>
          <p style="margin: 10px 0 0 0; color: #10b981; font-size: 28px; font-weight: bold;">${Math.round(metrics?.profitMargin || 0)}%</p>
        </div>
        <div style="background: #1f2937; padding: 20px; border-radius: 8px; border: 1px solid #374151;">
          <p style="margin: 0; color: #9ca3af; font-size: 12px; text-transform: uppercase;">Occupancy Rate</p>
          <p style="margin: 10px 0 0 0; color: #3b82f6; font-size: 28px; font-weight: bold;">${Math.round(metrics?.occupancyRate || 0)}%</p>
        </div>
      </div>

      ${revenueChartImg ? `
        <div style="margin-bottom: 30px;">
          <h2 style="color: #f3f4f6; margin-bottom: 15px; font-size: 20px;">Revenue Overview</h2>
          <img src="${revenueChartImg}" style="width: 100%; border-radius: 8px; border: 1px solid #374151;" />
        </div>
      ` : ''}

      ${clientChartImg ? `
        <div style="margin-bottom: 30px;">
          <h2 style="color: #f3f4f6; margin-bottom: 15px; font-size: 20px;">Revenue by Client</h2>
          <img src="${clientChartImg}" style="width: 100%; border-radius: 8px; border: 1px solid #374151;" />
        </div>
      ` : ''}

      ${recentInvoices?.length > 0 ? `
        <div style="margin-bottom: 30px;">
          <h2 style="color: #f3f4f6; margin-bottom: 15px; font-size: 20px;">Recent Invoices</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <thead>
              <tr style="background: #1f2937;">
                <th style="padding: 12px; text-align: left; color: #f97316;">Invoice #</th>
                <th style="padding: 12px; text-align: left; color: #f97316;">Client</th>
                <th style="padding: 12px; text-align: right; color: #f97316;">Amount</th>
                <th style="padding: 12px; text-align: center; color: #f97316;">Status</th>
              </tr>
            </thead>
            <tbody>
              ${recentInvoices.slice(0, 5).map(inv => `
                <tr style="border-bottom: 1px solid #374151;">
                  <td style="padding: 10px; color: #f3f4f6;">${inv.invoice_number || 'N/A'}</td>
                  <td style="padding: 10px; color: #f3f4f6;">${inv.client?.company_name || 'N/A'}</td>
                  <td style="padding: 10px; text-align: right; color: #f3f4f6; font-weight: bold;">${inv.total?.toFixed(2) || '0.00'} €</td>
                  <td style="padding: 10px; text-align: center;"><span style="padding: 4px 8px; border-radius: 12px; font-size: 11px; background: ${inv.status === 'paid' ? '#22c55e' : '#6b7280'}; color: white;">${inv.status}</span></td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>
      ` : ''}

      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #374151; text-align: center; color: #6b7280; font-size: 12px;">
        <p style="margin: 0;">Dashboard Report generated by CashPilot - ${new Date().toLocaleString('fr-FR')}</p>
      </div>
    </div>
  `;

  const tempDiv = document.createElement('div');
  tempDiv.innerHTML = content;
  document.body.appendChild(tempDiv);

  const options = {
    margin: 10,
    filename: `Dashboard_Report_${new Date().toISOString().split('T')[0]}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
  };

  try {
    await html2pdf().set(options).from(tempDiv).save();
    document.body.removeChild(tempDiv);
    return true;
  } catch (error) {
    document.body.removeChild(tempDiv);
    console.error('PDF export failed:', error);
    throw new Error('Failed to export PDF');
  }
};

/**
 * Export Dashboard to HTML
 */
export const exportDashboardHTML = (data, companyInfo) => {
  const { metrics, revenueData, clientRevenueData, recentInvoices, recentTimesheets } = data;

  const content = `
    <div style="font-family: Arial, sans-serif; max-width: 1000px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, #f97316 0%, #fb923c 100%); color: white; padding: 30px; border-radius: 8px; margin-bottom: 30px;">
        <h1>DASHBOARD REPORT</h1>
        <p>${companyInfo?.name || 'Your Company'} - ${new Date().toLocaleDateString('fr-FR')}</p>
      </div>

      <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 30px;">
        <div style="background: #1f2937; padding: 20px; border-radius: 8px;">
          <p style="color: #9ca3af; font-size: 12px;">TOTAL REVENUE</p>
          <p style="color: #f97316; font-size: 28px; font-weight: bold;">${metrics?.revenue?.toFixed(2) || '0.00'} €</p>
        </div>
        <div style="background: #1f2937; padding: 20px; border-radius: 8px;">
          <p style="color: #9ca3af; font-size: 12px;">PROFIT MARGIN</p>
          <p style="color: #10b981; font-size: 28px; font-weight: bold;">${Math.round(metrics?.profitMargin || 0)}%</p>
        </div>
        <div style="background: #1f2937; padding: 20px; border-radius: 8px;">
          <p style="color: #9ca3af; font-size: 12px;">OCCUPANCY RATE</p>
          <p style="color: #3b82f6; font-size: 28px; font-weight: bold;">${Math.round(metrics?.occupancyRate || 0)}%</p>
        </div>
      </div>

      ${revenueData?.length > 0 ? `
        <div style="margin-bottom: 30px;">
          <h2 style="color: #f3f4f6;">Revenue by Month</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <thead>
              <tr style="background: #1f2937; color: #f97316;">
                <th style="padding: 12px; text-align: left;">Month</th>
                <th style="padding: 12px; text-align: right;">Revenue</th>
              </tr>
            </thead>
            <tbody>
              ${revenueData.map(item => `
                <tr style="border-bottom: 1px solid #374151;">
                  <td style="padding: 10px; color: #f3f4f6;">${item.name}</td>
                  <td style="padding: 10px; text-align: right; color: #f3f4f6; font-weight: bold;">${item.revenue?.toFixed(2) || '0.00'} €</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>
      ` : ''}

      ${recentInvoices?.length > 0 ? `
        <div style="margin-bottom: 30px;">
          <h2 style="color: #f3f4f6;">Recent Invoices</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <thead>
              <tr style="background: #1f2937; color: #f97316;">
                <th style="padding: 12px; text-align: left;">Invoice #</th>
                <th style="padding: 12px; text-align: left;">Client</th>
                <th style="padding: 12px; text-align: right;">Amount</th>
                <th style="padding: 12px; text-align: center;">Status</th>
              </tr>
            </thead>
            <tbody>
              ${recentInvoices.slice(0, 5).map(inv => `
                <tr style="border-bottom: 1px solid #374151;">
                  <td style="padding: 10px; color: #f3f4f6;">${inv.invoice_number || 'N/A'}</td>
                  <td style="padding: 10px; color: #f3f4f6;">${inv.client?.company_name || 'N/A'}</td>
                  <td style="padding: 10px; text-align: right; color: #f3f4f6; font-weight: bold;">${inv.total?.toFixed(2) || '0.00'} €</td>
                  <td style="padding: 10px; text-align: center; color: #f3f4f6;">${inv.status}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>
      ` : ''}

      ${recentTimesheets?.length > 0 ? `
        <div style="margin-bottom: 30px;">
          <h2 style="color: #f3f4f6;">Recent Timesheets</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <thead>
              <tr style="background: #1f2937; color: #f97316;">
                <th style="padding: 12px; text-align: left;">Task</th>
                <th style="padding: 12px; text-align: left;">Project</th>
                <th style="padding: 12px; text-align: right;">Duration</th>
                <th style="padding: 12px; text-align: center;">Date</th>
              </tr>
            </thead>
            <tbody>
              ${recentTimesheets.slice(0, 5).map(ts => `
                <tr style="border-bottom: 1px solid #374151;">
                  <td style="padding: 10px; color: #f3f4f6;">${ts.task?.name || 'Untitled'}</td>
                  <td style="padding: 10px; color: #f3f4f6;">${ts.project?.name || 'N/A'}</td>
                  <td style="padding: 10px; text-align: right; color: #f3f4f6;">${Math.floor(ts.duration_minutes / 60)}h ${ts.duration_minutes % 60}m</td>
                  <td style="padding: 10px; text-align: center; color: #f3f4f6;">${new Date(ts.date).toLocaleDateString('fr-FR')}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>
      ` : ''}
    </div>
  `;

  const html = generateStandaloneHTML('Dashboard Report', content);
  downloadHTML(html, `Dashboard_${new Date().toISOString().split('T')[0]}`);
};

/**
 * Export Generic Report to HTML
 */
export const exportReportHTML = (reportType, companyInfo = {}) => {
  const content = `
    <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, #2563eb 0%, #3b82f6 100%); color: white; padding: 30px; border-radius: 8px; margin-bottom: 30px;">
        <h1>CASHPILOT ${reportType.charAt(0).toUpperCase() + reportType.slice(1).replace(/-/g, ' ')} REPORT</h1>
        <p>${companyInfo?.name || 'Your Company'} - ${new Date().toLocaleDateString('fr-FR')}</p>
      </div>

      <div style="padding: 20px; background: #1f2937; border-radius: 8px; margin-bottom: 20px;">
        <h2 style="color: #f3f4f6; margin-bottom: 15px;">Executive Summary</h2>
        <p style="color: #9ca3af;">This is an automated report generated by CashPilot.</p>
      </div>

      <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
        <thead>
          <tr style="background: #1f2937; color: #3b82f6;">
            <th style="padding: 12px; text-align: left; border: 1px solid #374151;">Metric</th>
            <th style="padding: 12px; text-align: right; border: 1px solid #374151;">Value</th>
          </tr>
        </thead>
        <tbody>
          <tr style="border-bottom: 1px solid #374151;">
            <td style="padding: 10px; color: #f3f4f6; border: 1px solid #374151;">Total Revenue</td>
            <td style="padding: 10px; text-align: right; color: #f3f4f6; font-weight: bold; border: 1px solid #374151;">$124,500.00</td>
          </tr>
          <tr style="border-bottom: 1px solid #374151;">
            <td style="padding: 10px; color: #f3f4f6; border: 1px solid #374151;">Active Projects</td>
            <td style="padding: 10px; text-align: right; color: #f3f4f6; font-weight: bold; border: 1px solid #374151;">14</td>
          </tr>
        </tbody>
      </table>
    </div>
  `;

  const html = generateStandaloneHTML(`CashPilot ${reportType} Report`, content);
  downloadHTML(html, `CashPilot_Report_${reportType}_${new Date().toISOString().split('T')[0]}`);
};
