import html2pdf from 'html2pdf.js';
import html2canvas from 'html2canvas';

/**
 * Capture chart/element as image
 */
const captureElementAsImage = async (elementId) => {
  const element = document.getElementById(elementId);
  if (!element) return null;

  try {
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#111827' // gray-900
    });
    return canvas.toDataURL('image/png');
  } catch (error) {
    console.error('Failed to capture element:', error);
    return null;
  }
};

/**
 * Export Analytics Dashboard to PDF
 */
export const exportAnalyticsPDF = async (data, companyInfo) => {
  // Capture charts as images
  const revenueChartImg = await captureElementAsImage('revenue-chart');
  const expensesChartImg = await captureElementAsImage('expenses-chart');
  const clientsChartImg = await captureElementAsImage('clients-chart');

  const content = `
    <div style="font-family: Arial, sans-serif; max-width: 1000px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, #8b5cf6 0%, #a78bfa 100%); color: white; padding: 30px; border-radius: 8px; margin-bottom: 30px;">
        <h1 style="margin: 0 0 10px 0; font-size: 32px;">ANALYTICS DASHBOARD</h1>
        <p style="margin: 0; font-size: 16px; opacity: 0.9;">${companyInfo?.name || 'Your Company'}</p>
        <p style="margin: 5px 0 0 0; font-size: 14px; opacity: 0.8;">${new Date().toLocaleDateString('fr-FR')}</p>
      </div>

      <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 30px;">
        <div style="background: #1f2937; padding: 20px; border-radius: 8px; border: 1px solid #374151;">
          <p style="margin: 0; color: #9ca3af; font-size: 12px; text-transform: uppercase;">Total Revenue</p>
          <p style="margin: 10px 0 0 0; color: #22c55e; font-size: 28px; font-weight: bold;">${data.totalRevenue?.toFixed(2) || '0.00'} €</p>
        </div>
        <div style="background: #1f2937; padding: 20px; border-radius: 8px; border: 1px solid #374151;">
          <p style="margin: 0; color: #9ca3af; font-size: 12px; text-transform: uppercase;">Total Expenses</p>
          <p style="margin: 10px 0 0 0; color: #ef4444; font-size: 28px; font-weight: bold;">${data.totalExpenses?.toFixed(2) || '0.00'} €</p>
        </div>
        <div style="background: #1f2937; padding: 20px; border-radius: 8px; border: 1px solid #374151;">
          <p style="margin: 0; color: #9ca3af; font-size: 12px; text-transform: uppercase;">Net Profit</p>
          <p style="margin: 10px 0 0 0; color: ${(data.totalRevenue - data.totalExpenses) >= 0 ? '#22c55e' : '#ef4444'}; font-size: 28px; font-weight: bold;">${((data.totalRevenue || 0) - (data.totalExpenses || 0)).toFixed(2)} €</p>
        </div>
      </div>

      ${revenueChartImg ? `
        <div style="margin-bottom: 30px;">
          <h2 style="color: #f3f4f6; margin-bottom: 15px; font-size: 20px;">Revenue Trends</h2>
          <img src="${revenueChartImg}" style="width: 100%; border-radius: 8px; border: 1px solid #374151;" />
        </div>
      ` : ''}

      ${expensesChartImg ? `
        <div style="margin-bottom: 30px;">
          <h2 style="color: #f3f4f6; margin-bottom: 15px; font-size: 20px;">Expenses Analysis</h2>
          <img src="${expensesChartImg}" style="width: 100%; border-radius: 8px; border: 1px solid #374151;" />
        </div>
      ` : ''}

      ${clientsChartImg ? `
        <div style="margin-bottom: 30px;">
          <h2 style="color: #f3f4f6; margin-bottom: 15px; font-size: 20px;">Revenue by Client</h2>
          <img src="${clientsChartImg}" style="width: 100%; border-radius: 8px; border: 1px solid #374151;" />
        </div>
      ` : ''}

      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #374151; text-align: center; color: #6b7280; font-size: 12px;">
        <p style="margin: 0;">Analytics Report generated by CashPilot - ${new Date().toLocaleString('fr-FR')}</p>
      </div>
    </div>
  `;

  const tempDiv = document.createElement('div');
  tempDiv.innerHTML = content;
  document.body.appendChild(tempDiv);

  const options = {
    margin: 10,
    filename: `Analytics_Report_${new Date().toISOString().split('T')[0]}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
  };

  try {
    await html2pdf().set(options).from(tempDiv).save();
    document.body.removeChild(tempDiv);
    return true;
  } catch (error) {
    document.body.removeChild(tempDiv);
    console.error('PDF export failed:', error);
    throw new Error('Failed to export PDF');
  }
};

/**
 * Export Supplier Report to PDF
 */
export const exportSupplierReportPDF = async (reportData, companyInfo) => {
  const content = `
    <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, #0ea5e9 0%, #38bdf8 100%); color: white; padding: 30px; border-radius: 8px; margin-bottom: 30px;">
        <h1 style="margin: 0 0 10px 0; font-size: 32px;">SUPPLIER REPORT</h1>
        <p style="margin: 0; font-size: 16px; opacity: 0.9;">${companyInfo?.name || 'Your Company'}</p>
        <p style="margin: 5px 0 0 0; font-size: 14px; opacity: 0.8;">${new Date().toLocaleDateString('fr-FR')}</p>
      </div>

      <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 30px;">
        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; border-left: 4px solid #0ea5e9;">
          <p style="margin: 0; color: #075985; font-size: 12px; text-transform: uppercase; font-weight: 600;">Total Spent</p>
          <p style="margin: 10px 0 0 0; color: #0c4a6e; font-size: 24px; font-weight: bold;">${reportData.totalSpent?.toFixed(2) || '0.00'} €</p>
        </div>
        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; border-left: 4px solid #3b82f6;">
          <p style="margin: 0; color: #075985; font-size: 12px; text-transform: uppercase; font-weight: 600;">Total Orders</p>
          <p style="margin: 10px 0 0 0; color: #0c4a6e; font-size: 24px; font-weight: bold;">${reportData.ordersCount || 0}</p>
        </div>
        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; border-left: 4px solid #22c55e;">
          <p style="margin: 0; color: #075985; font-size: 12px; text-transform: uppercase; font-weight: 600;">On-Time Delivery</p>
          <p style="margin: 10px 0 0 0; color: #0c4a6e; font-size: 24px; font-weight: bold;">${reportData.onTimeRate || '0'}%</p>
        </div>
      </div>

      ${reportData.topSuppliers?.length > 0 ? `
        <div style="margin-bottom: 30px;">
          <h2 style="color: #1e3a8a; margin-bottom: 15px; font-size: 20px; border-bottom: 2px solid #0ea5e9; padding-bottom: 10px;">Top Suppliers</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <thead>
              <tr style="background: #f3f4f6;">
                <th style="padding: 12px; text-align: left; border-bottom: 2px solid #0ea5e9; font-weight: 600;">Supplier</th>
                <th style="padding: 12px; text-align: right; border-bottom: 2px solid #0ea5e9; font-weight: 600;">Total Spent</th>
                <th style="padding: 12px; text-align: center; border-bottom: 2px solid #0ea5e9; font-weight: 600;">Orders</th>
              </tr>
            </thead>
            <tbody>
              ${reportData.topSuppliers.map(supplier => `
                <tr style="border-bottom: 1px solid #e5e7eb;">
                  <td style="padding: 10px;">${supplier.name || 'N/A'}</td>
                  <td style="padding: 10px; text-align: right; font-weight: 600;">${supplier.totalSpent?.toFixed(2) || '0.00'} €</td>
                  <td style="padding: 10px; text-align: center;">${supplier.ordersCount || 0}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>
      ` : ''}

      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; color: #6b7280; font-size: 12px;">
        <p style="margin: 0;">Supplier Report generated by CashPilot - ${new Date().toLocaleString('fr-FR')}</p>
      </div>
    </div>
  `;

  const tempDiv = document.createElement('div');
  tempDiv.innerHTML = content;
  document.body.appendChild(tempDiv);

  const options = {
    margin: 10,
    filename: `Supplier_Report_${new Date().toISOString().split('T')[0]}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
  };

  try {
    await html2pdf().set(options).from(tempDiv).save();
    document.body.removeChild(tempDiv);
    return true;
  } catch (error) {
    document.body.removeChild(tempDiv);
    console.error('PDF export failed:', error);
    throw new Error('Failed to export PDF');
  }
};

// ========== HTML EXPORT FUNCTIONS ==========

const downloadHTML = (html, filename) => {
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

const generateStandaloneHTML = (title, content) => {
  return `<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body { margin: 0; padding: 20px; background: #0f172a; color: #f1f5f9; font-family: Arial, sans-serif; }
    @media print { body { background: white; color: black; } }
  </style>
</head>
<body>
  ${content}
</body>
</html>`;
};

/**
 * Export Analytics to HTML
 */
export const exportAnalyticsHTML = async (data, companyInfo) => {
  // Note: HTML export won't include chart images, just data tables
  const content = `
    <div style="font-family: Arial, sans-serif; max-width: 1000px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, #8b5cf6 0%, #a78bfa 100%); color: white; padding: 30px; border-radius: 8px; margin-bottom: 30px;">
        <h1 style="margin: 0 0 10px 0;">ANALYTICS DASHBOARD</h1>
        <p style="margin: 0;">${companyInfo?.name || 'Your Company'} - ${new Date().toLocaleDateString('fr-FR')}</p>
      </div>
      <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px;">
        <div style="background: #1f2937; padding: 20px; border-radius: 8px;">
          <p style="color: #9ca3af; font-size: 12px;">TOTAL REVENUE</p>
          <p style="color: #22c55e; font-size: 28px; font-weight: bold;">${data.totalRevenue?.toFixed(2) || '0.00'} €</p>
        </div>
        <div style="background: #1f2937; padding: 20px; border-radius: 8px;">
          <p style="color: #9ca3af; font-size: 12px;">TOTAL EXPENSES</p>
          <p style="color: #ef4444; font-size: 28px; font-weight: bold;">${data.totalExpenses?.toFixed(2) || '0.00'} €</p>
        </div>
        <div style="background: #1f2937; padding: 20px; border-radius: 8px;">
          <p style="color: #9ca3af; font-size: 12px;">NET PROFIT</p>
          <p style="color: ${(data.totalRevenue - data.totalExpenses) >= 0 ? '#22c55e' : '#ef4444'}; font-size: 28px; font-weight: bold;">${((data.totalRevenue || 0) - (data.totalExpenses || 0)).toFixed(2)} €</p>
        </div>
      </div>
    </div>
  `;

  const html = generateStandaloneHTML('Analytics Dashboard', content);
  downloadHTML(html, `Analytics_${new Date().toISOString().split('T')[0]}`);
};

/**
 * Export Supplier Report to HTML
 */
export const exportSupplierReportHTML = (reportData, companyInfo) => {
  const content = `
    <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, #0ea5e9 0%, #38bdf8 100%); color: white; padding: 30px; border-radius: 8px; margin-bottom: 30px;">
        <h1>SUPPLIER REPORT</h1>
        <p>${companyInfo?.name || 'Your Company'} - ${new Date().toLocaleDateString('fr-FR')}</p>
      </div>
      <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 30px;">
        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; color: #0c4a6e;">
          <p style="font-size: 12px; font-weight: 600;">TOTAL SPENT</p>
          <p style="font-size: 24px; font-weight: bold;">${reportData.totalSpent?.toFixed(2) || '0.00'} €</p>
        </div>
        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; color: #0c4a6e;">
          <p style="font-size: 12px; font-weight: 600;">TOTAL ORDERS</p>
          <p style="font-size: 24px; font-weight: bold;">${reportData.ordersCount || 0}</p>
        </div>
        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; color: #0c4a6e;">
          <p style="font-size: 12px; font-weight: 600;">ON-TIME DELIVERY</p>
          <p style="font-size: 24px; font-weight: bold;">${reportData.onTimeRate || '0'}%</p>
        </div>
      </div>
      ${reportData.topSuppliers?.length > 0 ? `
        <h2 style="color: #1e3a8a;">Top Suppliers</h2>
        <table style="width: 100%; border-collapse: collapse;">
          <thead>
            <tr style="background: #f3f4f6; color: #111827;">
              <th style="padding: 12px; text-align: left;">Supplier</th>
              <th style="padding: 12px; text-align: right;">Total Spent</th>
              <th style="padding: 12px; text-align: center;">Orders</th>
            </tr>
          </thead>
          <tbody>
            ${reportData.topSuppliers.map(supplier => `
              <tr style="border-bottom: 1px solid #e5e7eb;">
                <td style="padding: 10px; color: #f1f5f9;">${supplier.name || 'N/A'}</td>
                <td style="padding: 10px; text-align: right; color: #f1f5f9;">${supplier.totalSpent?.toFixed(2) || '0.00'} €</td>
                <td style="padding: 10px; text-align: center; color: #f1f5f9;">${supplier.ordersCount || 0}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      ` : ''}
    </div>
  `;

  const html = generateStandaloneHTML('Supplier Report', content);
  downloadHTML(html, `Supplier_Report_${new Date().toISOString().split('T')[0]}`);
};
