import {
  Activity,
  ArrowRightLeft,
  BarChart3,
  CreditCard,
  DollarSign,
  Droplets,
  MoveDown,
  MoveUp,
  Scale,
  Sparkles,
  Target,
  TrendingUp,
  Wallet,
} from 'lucide-react';

export const STORAGE_KEY = 'cashpilot.financial-diagnostic-layout.v3';

export const COMPARISON_OPTIONS = {
  yoy: { label: 'N/N-1', sourceKey: 'yearOverYear' },
  mom: { label: 'M/M', sourceKey: 'monthOverMonth' },
  qoq: { label: 'T/T', sourceKey: 'quarterOverQuarter' },
};

export const SECTION_FILTERS = [
  { value: 'all', labelKey: 'financial_diagnostic.filter_all' },
  { value: 'margins', labelKey: 'financial_diagnostic.filter_margins' },
  { value: 'financing', labelKey: 'financial_diagnostic.filter_financing' },
  { value: 'ratios', labelKey: 'financial_diagnostic.filter_ratios' },
];

export const SORT_OPTIONS = [
  { value: 'custom', labelKey: 'financial_diagnostic.sort_custom' },
  { value: 'priority', labelKey: 'financial_diagnostic.sort_priority' },
  { value: 'value', labelKey: 'financial_diagnostic.sort_value' },
  { value: 'alpha', labelKey: 'financial_diagnostic.sort_alpha' },
];

export const DEFAULT_SECTOR_BENCHMARKS = {
  services: {
    grossMarginPercent: 42,
    ebitdaMargin: 14,
    operatingMargin: 11,
    netMargin: 8,
    roe: 15,
    roce: 11,
    currentRatio: 1.4,
    quickRatio: 1.1,
    cashRatio: 0.25,
    financialLeverage: 1.1,
    debtRatio: 1.1,
    autonomyRatio: 48,
    bfr: 25000,
    caf: 50000,
    operatingCashFlow: 32000,
  },
  commerce: {
    grossMarginPercent: 30,
    ebitdaMargin: 9,
    operatingMargin: 6,
    netMargin: 4,
    roe: 12,
    roce: 8,
    currentRatio: 1.2,
    quickRatio: 0.9,
    cashRatio: 0.2,
    financialLeverage: 1.4,
    debtRatio: 1.5,
    autonomyRatio: 41,
    bfr: 35000,
    caf: 42000,
    operatingCashFlow: 21000,
  },
  industrie: {
    grossMarginPercent: 36,
    ebitdaMargin: 13,
    operatingMargin: 9,
    netMargin: 6,
    roe: 13,
    roce: 10,
    currentRatio: 1.5,
    quickRatio: 1.0,
    cashRatio: 0.2,
    financialLeverage: 1.7,
    debtRatio: 1.8,
    autonomyRatio: 37,
    bfr: 50000,
    caf: 72000,
    operatingCashFlow: 38000,
  },
};

export const CARD_DEFINITIONS = [
  {
    id: 'revenue',
    i18nKey: 'revenue',
    section: 'margins',
    metricKey: 'revenue',
    format: 'currency',
    betterWhen: 'higher',
    trendKey: 'revenue',
    sourceGroup: 'revenue',
    icon: DollarSign,
    colorClass: 'text-blue-300',
    hasInfo: true,
  },
  {
    id: 'gross-margin',
    i18nKey: 'gross_margin',
    section: 'margins',
    metricKey: 'grossMargin',
    format: 'currency',
    betterWhen: 'higher',
    trendKey: 'margin',
    sourceGroup: 'expense',
    icon: Target,
    colorClass: 'text-emerald-300',
    hasInfo: true,
  },
  {
    id: 'gross-margin-rate',
    i18nKey: 'gross_margin_rate',
    section: 'margins',
    metricKey: 'grossMarginPercent',
    format: 'percentage',
    betterWhen: 'higher',
    trendKey: 'margin',
    sourceGroup: 'expense',
    icon: TrendingUp,
    colorClass: 'text-emerald-300',
  },
  {
    id: 'ebitda',
    i18nKey: 'ebitda',
    section: 'margins',
    metricKey: 'ebitda',
    format: 'currency',
    betterWhen: 'higher',
    trendKey: 'cashFlow',
    sourceGroup: 'expense',
    icon: Activity,
    colorClass: 'text-violet-300',
  },
  {
    id: 'ebitda-margin',
    i18nKey: 'ebitda_margin',
    section: 'margins',
    metricKey: 'ebitdaMargin',
    format: 'percentage',
    betterWhen: 'higher',
    trendKey: 'margin',
    sourceGroup: 'expense',
    icon: BarChart3,
    colorClass: 'text-violet-300',
  },
  {
    id: 'operating-result',
    i18nKey: 'operating_result',
    section: 'margins',
    metricKey: 'operatingResult',
    format: 'currency',
    betterWhen: 'higher',
    trendKey: 'cashFlow',
    sourceGroup: 'expense',
    icon: TrendingUp,
    colorClass: 'text-green-300',
  },
  {
    id: 'operating-margin',
    i18nKey: 'operating_margin',
    section: 'margins',
    metricKey: 'operatingMargin',
    format: 'percentage',
    betterWhen: 'higher',
    trendKey: 'margin',
    sourceGroup: 'expense',
    icon: Sparkles,
    colorClass: 'text-green-300',
  },
  {
    id: 'caf',
    i18nKey: 'caf',
    section: 'financing',
    metricKey: 'caf',
    format: 'currency',
    betterWhen: 'higher',
    trendKey: 'cashFlow',
    sourceGroup: 'cash',
    icon: Wallet,
    colorClass: 'text-emerald-300',
  },
  {
    id: 'working-capital',
    i18nKey: 'working_capital',
    section: 'financing',
    metricKey: 'workingCapital',
    format: 'currency',
    betterWhen: 'higher',
    trendKey: 'cashFlow',
    sourceGroup: 'liquidity',
    icon: CreditCard,
    colorClass: 'text-sky-300',
  },
  {
    id: 'bfr',
    i18nKey: 'bfr',
    section: 'financing',
    metricKey: 'bfr',
    format: 'currency',
    betterWhen: 'lower',
    trendKey: 'expense',
    sourceGroup: 'liquidity',
    icon: ArrowRightLeft,
    colorClass: 'text-orange-300',
  },
  {
    id: 'bfr-variation',
    i18nKey: 'bfr_variation',
    section: 'financing',
    metricKey: 'bfrVariation',
    format: 'currency',
    betterWhen: 'lower',
    trendKey: 'expense',
    sourceGroup: 'liquidity',
    icon: MoveUp,
    colorClass: 'text-orange-300',
  },
  {
    id: 'operating-cashflow',
    i18nKey: 'operating_cashflow',
    section: 'financing',
    metricKey: 'operatingCashFlow',
    format: 'currency',
    betterWhen: 'higher',
    trendKey: 'cashFlow',
    sourceGroup: 'cash',
    icon: Activity,
    colorClass: 'text-emerald-300',
  },
  {
    id: 'net-debt',
    i18nKey: 'net_debt',
    section: 'financing',
    metricKey: 'netDebt',
    format: 'currency',
    betterWhen: 'lower',
    trendKey: 'cashFlow',
    sourceGroup: 'debt',
    icon: CreditCard,
    colorClass: 'text-amber-300',
  },
  {
    id: 'debt-ratio',
    i18nKey: 'debt_ratio',
    section: 'financing',
    metricKey: 'debtRatio',
    format: 'number',
    betterWhen: 'lower',
    trendKey: 'expense',
    sourceGroup: 'debt',
    icon: Scale,
    colorClass: 'text-amber-300',
  },
  {
    id: 'debt-share',
    i18nKey: 'debt_share',
    section: 'financing',
    metricKey: 'debtShare',
    format: 'percentage',
    betterWhen: 'lower',
    trendKey: 'expense',
    sourceGroup: 'debt',
    icon: MoveDown,
    colorClass: 'text-amber-300',
  },
  {
    id: 'roe',
    i18nKey: 'roe',
    section: 'ratios',
    metricKey: 'roe',
    format: 'percentage',
    betterWhen: 'higher',
    trendKey: 'margin',
    sourceGroup: 'equity',
    icon: Target,
    colorClass: 'text-green-300',
  },
  {
    id: 'roce',
    i18nKey: 'roce',
    section: 'ratios',
    metricKey: 'roce',
    format: 'percentage',
    betterWhen: 'higher',
    trendKey: 'margin',
    sourceGroup: 'equity',
    icon: Target,
    colorClass: 'text-green-300',
  },
  {
    id: 'roa',
    i18nKey: 'roa',
    section: 'ratios',
    metricKey: 'roa',
    format: 'percentage',
    betterWhen: 'higher',
    trendKey: 'margin',
    sourceGroup: 'equity',
    icon: Activity,
    colorClass: 'text-green-300',
  },
  {
    id: 'net-margin',
    i18nKey: 'net_margin',
    section: 'ratios',
    metricKey: 'netMargin',
    format: 'percentage',
    betterWhen: 'higher',
    trendKey: 'margin',
    sourceGroup: 'expense',
    icon: Sparkles,
    colorClass: 'text-cyan-300',
  },
  {
    id: 'current-ratio',
    i18nKey: 'current_ratio',
    section: 'ratios',
    metricKey: 'currentRatio',
    format: 'number',
    betterWhen: 'higher',
    trendKey: 'cashFlow',
    sourceGroup: 'liquidity',
    icon: Droplets,
    colorClass: 'text-sky-300',
  },
  {
    id: 'quick-ratio',
    i18nKey: 'quick_ratio',
    section: 'ratios',
    metricKey: 'quickRatio',
    format: 'number',
    betterWhen: 'higher',
    trendKey: 'cashFlow',
    sourceGroup: 'liquidity',
    icon: Droplets,
    colorClass: 'text-sky-300',
  },
  {
    id: 'cash-ratio',
    i18nKey: 'cash_ratio',
    section: 'ratios',
    metricKey: 'cashRatio',
    format: 'number',
    betterWhen: 'higher',
    trendKey: 'cashFlow',
    sourceGroup: 'cash',
    icon: Droplets,
    colorClass: 'text-sky-300',
  },
  {
    id: 'financial-leverage',
    i18nKey: 'financial_leverage',
    section: 'ratios',
    metricKey: 'financialLeverage',
    format: 'number',
    betterWhen: 'lower',
    trendKey: 'expense',
    sourceGroup: 'debt',
    icon: Scale,
    colorClass: 'text-orange-300',
  },
  {
    id: 'autonomy-ratio',
    i18nKey: 'autonomy_ratio',
    section: 'ratios',
    metricKey: 'autonomyRatio',
    format: 'percentage',
    betterWhen: 'higher',
    trendKey: 'cashFlow',
    sourceGroup: 'equity',
    icon: Scale,
    colorClass: 'text-emerald-300',
  },
];

export const DEFAULT_CARD_ORDER = CARD_DEFINITIONS.map((card) => card.id);
