
export const COUNTRIES = [
  { code: 'AF', label: 'Afghanistan' },
  { code: 'ZA', label: 'Afrique du Sud' },
  { code: 'AL', label: 'Albanie' },
  { code: 'DZ', label: 'Algérie' },
  { code: 'DE', label: 'Allemagne' },
  { code: 'AD', label: 'Andorre' },
  { code: 'AO', label: 'Angola' },
  { code: 'SA', label: 'Arabie saoudite' },
  { code: 'AR', label: 'Argentine' },
  { code: 'AM', label: 'Arménie' },
  { code: 'AU', label: 'Australie' },
  { code: 'AT', label: 'Autriche' },
  { code: 'AZ', label: 'Azerbaïdjan' },
  { code: 'BH', label: 'Bahreïn' },
  { code: 'BD', label: 'Bangladesh' },
  { code: 'BE', label: 'Belgique' },
  { code: 'BJ', label: 'Bénin' },
  { code: 'BY', label: 'Biélorussie' },
  { code: 'BO', label: 'Bolivie' },
  { code: 'BA', label: 'Bosnie-Herzégovine' },
  { code: 'BW', label: 'Botswana' },
  { code: 'BR', label: 'Brésil' },
  { code: 'BN', label: 'Brunei' },
  { code: 'BG', label: 'Bulgarie' },
  { code: 'BF', label: 'Burkina Faso' },
  { code: 'BI', label: 'Burundi' },
  { code: 'KH', label: 'Cambodge' },
  { code: 'CM', label: 'Cameroun' },
  { code: 'CA', label: 'Canada' },
  { code: 'CV', label: 'Cap-Vert' },
  { code: 'CF', label: 'Centrafrique' },
  { code: 'CL', label: 'Chili' },
  { code: 'CN', label: 'Chine' },
  { code: 'CY', label: 'Chypre' },
  { code: 'CO', label: 'Colombie' },
  { code: 'KM', label: 'Comores' },
  { code: 'CG', label: 'Congo' },
  { code: 'CD', label: 'Congo (RDC)' },
  { code: 'KR', label: 'Corée du Sud' },
  { code: 'CR', label: 'Costa Rica' },
  { code: 'CI', label: "Côte d'Ivoire" },
  { code: 'HR', label: 'Croatie' },
  { code: 'CU', label: 'Cuba' },
  { code: 'DK', label: 'Danemark' },
  { code: 'DJ', label: 'Djibouti' },
  { code: 'DM', label: 'Dominique' },
  { code: 'EG', label: 'Égypte' },
  { code: 'AE', label: 'Émirats arabes unis' },
  { code: 'EC', label: 'Équateur' },
  { code: 'ER', label: 'Érythrée' },
  { code: 'ES', label: 'Espagne' },
  { code: 'EE', label: 'Estonie' },
  { code: 'US', label: 'États-Unis' },
  { code: 'ET', label: 'Éthiopie' },
  { code: 'FI', label: 'Finlande' },
  { code: 'FR', label: 'France' },
  { code: 'GA', label: 'Gabon' },
  { code: 'GM', label: 'Gambie' },
  { code: 'GE', label: 'Géorgie' },
  { code: 'GH', label: 'Ghana' },
  { code: 'GR', label: 'Grèce' },
  { code: 'GT', label: 'Guatemala' },
  { code: 'GN', label: 'Guinée' },
  { code: 'GQ', label: 'Guinée équatoriale' },
  { code: 'GW', label: 'Guinée-Bissau' },
  { code: 'GY', label: 'Guyana' },
  { code: 'HT', label: 'Haïti' },
  { code: 'HN', label: 'Honduras' },
  { code: 'HK', label: 'Hong Kong' },
  { code: 'HU', label: 'Hongrie' },
  { code: 'IN', label: 'Inde' },
  { code: 'ID', label: 'Indonésie' },
  { code: 'IQ', label: 'Irak' },
  { code: 'IR', label: 'Iran' },
  { code: 'IE', label: 'Irlande' },
  { code: 'IS', label: 'Islande' },
  { code: 'IL', label: 'Israël' },
  { code: 'IT', label: 'Italie' },
  { code: 'JM', label: 'Jamaïque' },
  { code: 'JP', label: 'Japon' },
  { code: 'JO', label: 'Jordanie' },
  { code: 'KZ', label: 'Kazakhstan' },
  { code: 'KE', label: 'Kenya' },
  { code: 'KG', label: 'Kirghizistan' },
  { code: 'KW', label: 'Koweït' },
  { code: 'LA', label: 'Laos' },
  { code: 'LV', label: 'Lettonie' },
  { code: 'LB', label: 'Liban' },
  { code: 'LR', label: 'Liberia' },
  { code: 'LY', label: 'Libye' },
  { code: 'LI', label: 'Liechtenstein' },
  { code: 'LT', label: 'Lituanie' },
  { code: 'LU', label: 'Luxembourg' },
  { code: 'MK', label: 'Macédoine du Nord' },
  { code: 'MG', label: 'Madagascar' },
  { code: 'MY', label: 'Malaisie' },
  { code: 'MW', label: 'Malawi' },
  { code: 'ML', label: 'Mali' },
  { code: 'MT', label: 'Malte' },
  { code: 'MA', label: 'Maroc' },
  { code: 'MU', label: 'Maurice' },
  { code: 'MR', label: 'Mauritanie' },
  { code: 'MX', label: 'Mexique' },
  { code: 'MD', label: 'Moldavie' },
  { code: 'MC', label: 'Monaco' },
  { code: 'MN', label: 'Mongolie' },
  { code: 'ME', label: 'Monténégro' },
  { code: 'MZ', label: 'Mozambique' },
  { code: 'MM', label: 'Myanmar' },
  { code: 'NA', label: 'Namibie' },
  { code: 'NP', label: 'Népal' },
  { code: 'NI', label: 'Nicaragua' },
  { code: 'NE', label: 'Niger' },
  { code: 'NG', label: 'Nigeria' },
  { code: 'NO', label: 'Norvège' },
  { code: 'NZ', label: 'Nouvelle-Zélande' },
  { code: 'OM', label: 'Oman' },
  { code: 'UG', label: 'Ouganda' },
  { code: 'UZ', label: 'Ouzbékistan' },
  { code: 'PK', label: 'Pakistan' },
  { code: 'PA', label: 'Panama' },
  { code: 'PY', label: 'Paraguay' },
  { code: 'NL', label: 'Pays-Bas' },
  { code: 'PE', label: 'Pérou' },
  { code: 'PH', label: 'Philippines' },
  { code: 'PL', label: 'Pologne' },
  { code: 'PT', label: 'Portugal' },
  { code: 'QA', label: 'Qatar' },
  { code: 'RO', label: 'Roumanie' },
  { code: 'UK', label: 'Royaume-Uni' },
  { code: 'RU', label: 'Russie' },
  { code: 'RW', label: 'Rwanda' },
  { code: 'SN', label: 'Sénégal' },
  { code: 'RS', label: 'Serbie' },
  { code: 'SL', label: 'Sierra Leone' },
  { code: 'SG', label: 'Singapour' },
  { code: 'SK', label: 'Slovaquie' },
  { code: 'SI', label: 'Slovénie' },
  { code: 'SO', label: 'Somalie' },
  { code: 'SD', label: 'Soudan' },
  { code: 'LK', label: 'Sri Lanka' },
  { code: 'SE', label: 'Suède' },
  { code: 'CH', label: 'Suisse' },
  { code: 'SY', label: 'Syrie' },
  { code: 'TW', label: 'Taïwan' },
  { code: 'TZ', label: 'Tanzanie' },
  { code: 'TD', label: 'Tchad' },
  { code: 'CZ', label: 'Tchéquie' },
  { code: 'TH', label: 'Thaïlande' },
  { code: 'TG', label: 'Togo' },
  { code: 'TN', label: 'Tunisie' },
  { code: 'TM', label: 'Turkménistan' },
  { code: 'TR', label: 'Turquie' },
  { code: 'UA', label: 'Ukraine' },
  { code: 'UY', label: 'Uruguay' },
  { code: 'VE', label: 'Venezuela' },
  { code: 'VN', label: 'Viêt Nam' },
  { code: 'YE', label: 'Yémen' },
  { code: 'ZM', label: 'Zambie' },
  { code: 'ZW', label: 'Zimbabwe' },
];
