
import { useState, useEffect, useMemo, useCallback } from 'react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/context/AuthContext';
import {
  calculateRevenue,
  calculateRevenueTTC,
  calculateExpenses,
  calculateNetIncome,
  calculateOutputVAT,
  calculateInputVAT,
  calculateVATPayable,
  calculateVATBreakdown,
  buildBalanceSheet,
  buildIncomeStatement,
  estimateTax,
  buildMonthlyChartData,
  DEFAULT_TAX_BRACKETS,
  // Entry-based functions
  buildTrialBalance,
  buildBalanceSheetFromEntries,
  buildIncomeStatementFromEntries,
  buildGeneralLedger,
  buildJournalBook,
  calculateRevenueFromEntries,
  calculateExpensesFromEntries,
  calculateNetIncomeFromEntries,
  calculateOutputVATFromEntries,
  calculateInputVATFromEntries,
  calculateVATBreakdownFromEntries,
  buildMonthlyChartDataFromEntries,
  validateAccountingConsistency,
} from '@/utils/accountingCalculations';
import { buildFinancialDiagnostic } from '@/utils/financialAnalysisCalculations';

export const useAccountingData = (startDate, endDate) => {
  const { user } = useAuth();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Raw data
  const [invoices, setInvoices] = useState([]);
  const [expenses, setExpenses] = useState([]);
  const [supplierInvoices, setSupplierInvoices] = useState([]);
  const [accounts, setAccounts] = useState([]);
  const [mappings, setMappings] = useState([]);
  const [taxRates, setTaxRates] = useState([]);
  const [entries, setEntries] = useState([]);

  const fetchAll = useCallback(async () => {
    if (!user || !supabase) {
      setLoading(false);
      return;
    }

    try {
      setLoading(true);
      setError(null);

      const [invRes, expRes, supRes, accRes, mapRes, taxRes, entRes] = await Promise.all([
        supabase.from('invoices').select('*').order('date', { ascending: false }),
        supabase.from('expenses').select('*').order('date', { ascending: false }),
        (async () => { try { return await supabase.from('supplier_invoices').select('*').order('created_at', { ascending: false }); } catch { return { data: [], error: null }; } })(),
        supabase.from('accounting_chart_of_accounts').select('*').order('account_code', { ascending: true }),
        supabase.from('accounting_mappings').select('*'),
        supabase.from('accounting_tax_rates').select('*'),
        // Fetch accounting entries
        supabase.from('accounting_entries').select('*').order('transaction_date', { ascending: false }),
      ]);

      setInvoices(invRes.data || []);
      setExpenses(expRes.data || []);
      setSupplierInvoices(supRes?.data || []);
      setAccounts(accRes.data || []);
      setMappings(mapRes.data || []);
      setTaxRates(taxRes.data || []);
      setEntries(entRes.data || []);
    } catch (err) {
      console.error('Error fetching accounting data:', err);
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }, [user]);

  useEffect(() => {
    fetchAll();
  }, [fetchAll]);

  // Real-time subscriptions for automatic updates with debouncing
  useEffect(() => {
    if (!user || !supabase) return;

    let refreshTimeout = null;

    // Debounced refresh to avoid multiple rapid updates
    const debouncedRefresh = () => {
      if (refreshTimeout) clearTimeout(refreshTimeout);
      refreshTimeout = setTimeout(() => {
        fetchAll();
      }, 500); // Wait 500ms after last change before refreshing
    };

    // Subscribe to accounting entries changes (auto-generated by triggers)
    const entriesSubscription = supabase
      .channel('accounting_entries_changes')
      .on('postgres_changes',
        { event: '*', schema: 'public', table: 'accounting_entries', filter: `user_id=eq.${user.id}` },
        (payload) => {
          console.log('Accounting entry changed:', payload.eventType);
          debouncedRefresh();
        }
      )
      .subscribe();

    // Subscribe to invoices changes
    const invoicesSubscription = supabase
      .channel('invoices_changes')
      .on('postgres_changes',
        { event: '*', schema: 'public', table: 'invoices', filter: `user_id=eq.${user.id}` },
        (payload) => {
          console.log('Invoice changed:', payload.eventType);
          debouncedRefresh();
        }
      )
      .subscribe();

    // Subscribe to expenses changes
    const expensesSubscription = supabase
      .channel('expenses_changes')
      .on('postgres_changes',
        { event: '*', schema: 'public', table: 'expenses', filter: `user_id=eq.${user.id}` },
        (payload) => {
          console.log('Expense changed:', payload.eventType);
          debouncedRefresh();
        }
      )
      .subscribe();

    // Subscribe to payments changes
    const paymentsSubscription = supabase
      .channel('payments_changes')
      .on('postgres_changes',
        { event: '*', schema: 'public', table: 'payments', filter: `user_id=eq.${user.id}` },
        (payload) => {
          console.log('Payment changed:', payload.eventType);
          debouncedRefresh();
        }
      )
      .subscribe();

    // Cleanup subscriptions and timeout on unmount
    return () => {
      if (refreshTimeout) clearTimeout(refreshTimeout);
      entriesSubscription.unsubscribe();
      invoicesSubscription.unsubscribe();
      expensesSubscription.unsubscribe();
      paymentsSubscription.unsubscribe();
    };
  }, [user, fetchAll]);

  // Determine if we have auto-generated entries
  const hasAutoEntries = useMemo(() => {
    return entries.some(e => e.is_auto === true);
  }, [entries]);

  // Computed values (memoized)
  const computed = useMemo(() => {
    if (!startDate || !endDate) return null;

    const useEntries = hasAutoEntries && entries.length > 0;

    // KPI calculations: use entry-based when auto-entries are active
    let revenue, revenueTTC, totalExpenses, netIncome;
    let outputVAT, inputVAT, vatPayable, vatBreakdown;
    let taxEstimate, monthlyData;

    if (useEntries) {
      // Entry-based: single source of truth from accounting_entries
      revenue = calculateRevenueFromEntries(entries, accounts, startDate, endDate);
      revenueTTC = revenue; // In entry-based mode, entries already include TTC via separate account
      totalExpenses = calculateExpensesFromEntries(entries, accounts, startDate, endDate);
      netIncome = calculateNetIncomeFromEntries(entries, accounts, startDate, endDate);

      outputVAT = calculateOutputVATFromEntries(entries, accounts, startDate, endDate);
      inputVAT = calculateInputVATFromEntries(entries, accounts, startDate, endDate);
      vatPayable = outputVAT - inputVAT;
      vatBreakdown = calculateVATBreakdownFromEntries(entries, accounts, startDate, endDate);

      taxEstimate = estimateTax(netIncome > 0 ? netIncome : 0);
      monthlyData = buildMonthlyChartDataFromEntries(entries, accounts, startDate, endDate);
    } else {
      // Legacy: calculate from invoices/expenses tables
      revenue = calculateRevenue(invoices, startDate, endDate);
      revenueTTC = calculateRevenueTTC(invoices, startDate, endDate);
      totalExpenses = calculateExpenses(expenses, supplierInvoices, startDate, endDate);
      netIncome = calculateNetIncome(invoices, expenses, supplierInvoices, startDate, endDate);

      outputVAT = calculateOutputVAT(invoices, startDate, endDate);
      inputVAT = calculateInputVAT(expenses, supplierInvoices, startDate, endDate);
      vatPayable = calculateVATPayable(outputVAT, inputVAT);
      vatBreakdown = calculateVATBreakdown(invoices, expenses, startDate, endDate);

      taxEstimate = estimateTax(netIncome > 0 ? netIncome : 0);
      monthlyData = buildMonthlyChartData(invoices, expenses, startDate, endDate);
    }

    // Balance sheet & income statement: always entry-based when available
    let balanceSheet, incomeStatement;
    if (useEntries) {
      balanceSheet = buildBalanceSheetFromEntries(accounts, entries, startDate, endDate);
      incomeStatement = buildIncomeStatementFromEntries(accounts, entries, startDate, endDate);
    } else {
      balanceSheet = buildBalanceSheet(accounts, invoices, expenses, supplierInvoices, mappings, startDate, endDate);
      incomeStatement = buildIncomeStatement(accounts, invoices, expenses, supplierInvoices, mappings, startDate, endDate);
    }

    // Entry-based reports
    const trialBalance = buildTrialBalance(entries, accounts);
    const generalLedger = buildGeneralLedger(entries, accounts, startDate, endDate);
    const journalBook = buildJournalBook(entries, startDate, endDate);

    // Financial diagnostic
    const financialDiagnostic = buildFinancialDiagnostic(
      entries,
      accounts,
      balanceSheet,
      incomeStatement,
      startDate,
      endDate,
      null // previousPeriodData pour comparaisons futures
    );

    // Consistency validation
    const consistencyWarnings = validateAccountingConsistency(
      { revenue, totalExpenses, netIncome },
      incomeStatement
    );
    if (consistencyWarnings.length > 0) {
      console.warn('Accounting consistency warnings:', consistencyWarnings);
    }

    return {
      revenue,
      revenueTTC,
      totalExpenses,
      netIncome,
      outputVAT,
      inputVAT,
      vatPayable,
      vatBreakdown,
      balanceSheet,
      incomeStatement,
      taxEstimate,
      monthlyData,
      trialBalance,
      generalLedger,
      journalBook,
      financialDiagnostic,
      consistencyWarnings,
    };
  }, [invoices, expenses, supplierInvoices, accounts, mappings, entries, hasAutoEntries, startDate, endDate]);

  return {
    loading,
    error,
    // Raw data
    invoices,
    expenses,
    supplierInvoices,
    accounts,
    mappings,
    taxRates,
    entries,
    hasAutoEntries,
    // Computed values
    ...(computed || {
      revenue: 0,
      revenueTTC: 0,
      totalExpenses: 0,
      netIncome: 0,
      outputVAT: 0,
      inputVAT: 0,
      vatPayable: 0,
      vatBreakdown: { output: [], input: [] },
      balanceSheet: { assets: [], liabilities: [], equity: [], totalAssets: 0, totalLiabilities: 0, totalEquity: 0, balanced: true },
      incomeStatement: { revenueItems: [], expenseItems: [], totalRevenue: 0, totalExpenses: 0, netIncome: 0 },
      taxEstimate: { totalTax: 0, effectiveRate: 0, details: [], quarterlyPayment: 0 },
      monthlyData: [],
      trialBalance: [],
      generalLedger: [],
      journalBook: [],
      financialDiagnostic: null,
      consistencyWarnings: [],
    }),
    refresh: fetchAll
  };
};
