import { createClient } from "@supabase/supabase-js";
import { readFileSync } from "fs";
const env:Record<string,string>={};const ef=new URL("./.env",import.meta.url);
readFileSync(ef,"utf8").split("\n").forEach(l=>{const[k,...v]=l.split("=");if(k)env[k.trim()]=v.join("=").trim();});
const SU=env["SUPABASE_URL"]||"";const SK=env["SUPABASE_ANON_KEY"]||"";const supabase=createClient(SU,SK);
const TE="scte.test@cashpilot.cloud",TP="ScteTest@123";
type TR={id:string;description:string;status:"PASS"|"FAIL";detail:string};const R:TR[]=[];let cCli="",cInv="",cPay="",userId="";
function add(id:string,d:string,p:boolean,dt:string){R.push({id,description:d,status:p?"PASS":"FAIL",detail:dt});}
async function runTests(){
try{const{data,error}=await supabase.auth.signInWithPassword({email:TE,password:TP});const p=!error&&!!data?.user?.id;if(data?.user?.id)userId=data.user.id;add("A2-AUTH-01","Login SCTE",p,p?"user_id: "+data.user.id:"Error: "+error?.message);}catch(e){add("A2-AUTH-01","Login SCTE",false,String(e));}
try{const{data:{user}}=await supabase.auth.getUser();add("A2-AUTH-02","Whoami",!!user&&user.email===TE,user?"email: "+user.email:"Not authenticated");}catch(e){add("A2-AUTH-02","Whoami",false,String(e));}
try{const tmp=createClient(SU,SK);const{error}=await tmp.auth.signInWithPassword({email:TE,password:"wrong"});add("A2-AUTH-03","Login mauvais mot de passe",!!error,error?"Error correctly returned: "+error.message:"No error");}catch(e){add("A2-AUTH-03","Login mauvais mot de passe",false,String(e));}
try{const{data,error}=await supabase.from("clients").select("*");add("A2-CLI-01","Lister clients",!error&&data!==null,!error?(data?.length||0)+" clients":"Error: "+error?.message);}catch(e){add("A2-CLI-01","Lister clients",false,String(e));}
try{const{data,error}=await supabase.from("clients").insert({company_name:"Test Client SCTE",contact_name:"Jean Dupont",email:"jean@test-scte.fr",city:"Bruxelles",user_id:userId}).select().single();if(data?.id)cCli=data.id;add("A2-CLI-02","Creer client",!error&&!!data?.id,!error?"id: "+data?.id+", name: "+data?.company_name:"Error: "+error?.message);}catch(e){add("A2-CLI-02","Creer client",false,String(e));}
try{if(!cCli)throw new Error("No client");const{data,error}=await supabase.from("clients").select("*").eq("id",cCli).single();add("A2-CLI-03","Recuperer client",!error&&data?.company_name==="Test Client SCTE",!error?"company_name: "+data?.company_name:"Error: "+error?.message);}catch(e){add("A2-CLI-03","Recuperer client",false,String(e));}
try{const{data,error}=await supabase.from("clients").select("*").ilike("company_name","%Test Client SCTE%");add("A2-CLI-04","Chercher client",!error&&!!data&&data.length>0,!error?"Found "+(data?.length||0)+" matching":"Error: "+error?.message);}catch(e){add("A2-CLI-04","Chercher client",false,String(e));}
try{if(!cCli)throw new Error("No client");const{data:inv,error}=await supabase.from("invoices").select("total_ttc,payment_status").eq("client_id",cCli);add("A2-CLI-05","Solde client",!error,!error?(inv?.length||0)+" invoices for balance":"Error: "+error?.message);}catch(e){add("A2-CLI-05","Solde client",false,String(e));}
try{const{data,error}=await supabase.from("invoices").select("*");add("A2-INV-01","Lister factures",!error&&data!==null,!error?(data?.length||0)+" factures":"Error: "+error?.message);}catch(e){add("A2-INV-01","Lister factures",false,String(e));}
try{const{data,error}=await supabase.from("invoices").select("*").eq("status","draft");add("A2-INV-02","Lister par statut draft",!error&&data!==null&&data.every((i:any)=>i.status==="draft"),!error?(data?.length||0)+" factures draft":"Error: "+error?.message);}catch(e){add("A2-INV-02","Lister par statut draft",false,String(e));}
try{const{data,error}=await supabase.from("invoices").insert({invoice_number:"TEST-SCTE-001",client_id:cCli||null,issue_date:"2026-02-09",due_date:"2026-03-09",total_ht:1000,total_ttc:1200,status:"draft",user_id:userId}).select().single();if(data?.id)cInv=data.id;add("A2-INV-03","Creer facture",!error&&!!data?.id,!error?"id: "+data?.id+", number: "+data?.invoice_number:"Error: "+error?.message);}catch(e){add("A2-INV-03","Creer facture",false,String(e));}
try{if(!cInv)throw new Error("No invoice");const{data,error}=await supabase.from("invoices").select("*,client:clients(company_name)").eq("id",cInv).single();add("A2-INV-04","Recuperer facture",!error&&data?.invoice_number==="TEST-SCTE-001",!error?"number: "+data?.invoice_number+", client: "+(data as any)?.client?.company_name:"Error: "+error?.message);}catch(e){add("A2-INV-04","Recuperer facture",false,String(e));}
try{if(!cInv)throw new Error("No invoice");const{data,error}=await supabase.from("invoices").update({status:"sent"}).eq("id",cInv).select().single();add("A2-INV-05","Mettre a jour statut",!error&&data?.status==="sent",!error?"status: "+data?.status:"Error: "+error?.message);}catch(e){add("A2-INV-05","Mettre a jour statut",false,String(e));}
try{const{data,error}=await supabase.from("invoices").select("*").or("invoice_number.ilike.%TEST-SCTE%,notes.ilike.%TEST-SCTE%");add("A2-INV-06","Rechercher factures",!error&&!!data&&data.some((i:any)=>i.invoice_number==="TEST-SCTE-001"),!error?"Found "+(data?.length||0)+" matching":"Error: "+error?.message);}catch(e){add("A2-INV-06","Rechercher factures",false,String(e));}
try{const{data,error}=await supabase.from("invoices").select("total_ttc,status,payment_status");const total=data?.reduce((s:number,i:any)=>s+(i.total_ttc||0),0)||0;const paid=data?.filter((i:any)=>i.status==="paid"||i.payment_status==="paid").reduce((s:number,i:any)=>s+(i.total_ttc||0),0)||0;add("A2-INV-07","Stats factures",!error&&data!==null,!error?"total: "+total+", paid: "+paid:"Error: "+error?.message);}catch(e){add("A2-INV-07","Stats factures",false,String(e));}
try{const{data,error}=await supabase.from("invoices").select("*").limit(2);add("A2-INV-08","Lister avec limite",!error&&data!==null&&data.length<=2,!error?(data?.length||0)+" factures (limit 2)":"Error: "+error?.message);}catch(e){add("A2-INV-08","Lister avec limite",false,String(e));}
try{const{data,error}=await supabase.from("payments").select("*");add("A2-PAY-01","Lister paiements",!error&&data!==null,!error?(data?.length||0)+" paiements":"Error: "+error?.message);}catch(e){add("A2-PAY-01","Lister paiements",false,String(e));}
try{if(!cInv)throw new Error("No invoice");const{data,error}=await supabase.from("payments").insert({invoice_id:cInv,amount:500,payment_method:"bank_transfer",payment_date:"2026-02-09",user_id:userId}).select().single();if(data?.id)cPay=data.id;const{data:inv}=await supabase.from("invoices").select("payment_status").eq("id",cInv).single();add("A2-PAY-02","Paiement partiel",!error&&!!data?.id,!error?"payment_id: "+data?.id+", ps: "+inv?.payment_status:"Error: "+error?.message);}catch(e){add("A2-PAY-02","Paiement partiel",false,String(e));}
try{if(!cInv)throw new Error("No invoice");const{data,error}=await supabase.from("payments").insert({invoice_id:cInv,amount:700,payment_method:"bank_transfer",payment_date:"2026-02-09",user_id:userId}).select().single();const{data:inv}=await supabase.from("invoices").select("payment_status").eq("id",cInv).single();add("A2-PAY-03","Paiement solde",!error&&!!data?.id,!error?"payment_id: "+data?.id+", ps: "+inv?.payment_status:"Error: "+error?.message);}catch(e){add("A2-PAY-03","Paiement solde",false,String(e));}
try{const{data,error}=await supabase.from("invoices").select("*").in("payment_status",["unpaid","partial"]).in("status",["sent","overdue"]);add("A2-PAY-04","Factures impayees",!error&&data!==null,!error?(data?.length||0)+" impayees":"Error: "+error?.message);}catch(e){add("A2-PAY-04","Factures impayees",false,String(e));}
try{const{data:invoices,error}=await supabase.from("invoices").select("total_ttc,payment_status,status");const td=invoices?.filter((i:any)=>i.payment_status!=="paid").reduce((s:number,i:any)=>s+(i.total_ttc||0),0)||0;add("A2-PAY-05","Resume creances",!error&&invoices!==null,!error?"total_due: "+td:"Error: "+error?.message);}catch(e){add("A2-PAY-05","Resume creances",false,String(e));}
try{const{data,error}=await supabase.from("chart_of_accounts").select("*");add("A2-ACC-01","Plan comptable",!error,!error?(data?.length||0)+" comptes":"Error: "+error?.message);}catch(e){add("A2-ACC-01","Plan comptable",false,String(e));}
try{const{data:ex}=await supabase.from("chart_of_accounts").select("id").limit(1);add("A2-ACC-02","Init comptabilite FR",true,ex&&ex.length>0?"Deja initialise":"Table accessible");}catch(e){add("A2-ACC-02","Init comptabilite FR",false,String(e));}
try{const{data,error}=await supabase.from("chart_of_accounts").select("*");add("A2-ACC-03","Plan comptable apres init",!error,!error?(data?.length||0)+" comptes":"Error: "+error?.message);}catch(e){add("A2-ACC-03","Plan comptable apres init",false,String(e));}
try{const{data,error}=await supabase.from("accounting_entries").select("*").gte("entry_date","2026-01-01").lte("entry_date","2026-02-28");add("A2-ACC-04","Ecritures comptables",!error,!error?(data?.length||0)+" ecritures":"Error: "+error?.message);}catch(e){add("A2-ACC-04","Ecritures comptables",false,String(e));}
try{const{data,error}=await supabase.from("accounting_entries").select("account_code,debit,credit").gte("entry_date","2026-01-01").lte("entry_date","2026-02-28");add("A2-ACC-05","Resume TVA",!error,!error?(data?.length||0)+" entries for tax calc":"Error: "+error?.message);}catch(e){add("A2-ACC-05","Resume TVA",false,String(e));}
try{const{data,error}=await supabase.from("invoices").select("issue_date,total_ttc");add("A2-ANA-01","Cash flow 6 mois",!error&&data!==null,!error?(data?.length||0)+" invoices for cash flow":"Error: "+error?.message);}catch(e){add("A2-ANA-01","Cash flow 6 mois",false,String(e));}
try{const{data:inv,error:e1}=await supabase.from("invoices").select("total_ttc,status");const{data:exp,error:e2}=await supabase.from("expenses").select("amount");add("A2-ANA-02","KPIs dashboard",!e1&&!e2,!e1&&!e2?"invoices: "+(inv?.length||0)+", expenses: "+(exp?.length||0):"Error: "+(e1?.message||e2?.message));}catch(e){add("A2-ANA-02","KPIs dashboard",false,String(e));}
try{const{data,error}=await supabase.from("invoices").select("client_id,total_ttc,client:clients(company_name)").limit(3);add("A2-ANA-03","Top clients",!error&&data!==null,!error?(data?.length||0)+" entries":"Error: "+error?.message);}catch(e){add("A2-ANA-03","Top clients",false,String(e));}
try{const{data,error}=await supabase.from("accounting_entries").select("*").gte("entry_date","2026-01-01").lte("entry_date","2026-02-28");add("A2-EXP-01","Export FEC (data)",!error,!error?(data?.length||0)+" entries for FEC":"Error: "+error?.message);}catch(e){add("A2-EXP-01","Export FEC",false,String(e));}
try{const{data,error}=await supabase.from("accounting_entries").select("*").gte("entry_date","2026-01-01").lte("entry_date","2026-02-28");add("A2-EXP-02","Export SAF-T (data)",!error,!error?(data?.length||0)+" entries for SAF-T":"Error: "+error?.message);}catch(e){add("A2-EXP-02","Export SAF-T",false,String(e));}
try{if(!cInv)throw new Error("No invoice");const{data,error}=await supabase.from("invoices").select("*,client:clients(*),items:invoice_items(*)").eq("id",cInv).single();const p=!error&&!!data;add("A2-EXP-03","Export Factur-X MINIMUM (data)",p,p?"Invoice data loaded":"Error: "+error?.message);add("A2-EXP-04","Export Factur-X BASIC (data)",p,p?"Same data, BASIC":"Error: "+error?.message);add("A2-EXP-05","Export Factur-X EN16931 (data)",p,p?"Same data, EN16931":"Error: "+error?.message);}catch(e){add("A2-EXP-03","Export Factur-X MINIMUM",false,String(e));add("A2-EXP-04","Export Factur-X BASIC",false,String(e));add("A2-EXP-05","Export Factur-X EN16931",false,String(e));}
try{const tables=["invoices","clients","payments","expenses","quotes","projects"];let allP=true,totalR=0;for(const t of tables){const{data,error}=await supabase.from(t).select("*");if(error){allP=false;break;}totalR+=data?.length||0;}add("A2-EXP-06","Backup complet",allP,allP?totalR+" total rows across "+tables.length+" tables":"Error during backup");}catch(e){add("A2-EXP-06","Backup complet",false,String(e));}
console.log("=== AGENT 2 SCTE SRL TEST RESULTS ===");console.log(JSON.stringify(R,null,2));const passed=R.filter(r=>r.status==="PASS").length;console.log("\n=== SUMMARY: "+passed+"/"+R.length+" PASS ===");console.log("\n=== CREATED IDS ===");console.log(JSON.stringify({createdClientId:cCli,createdInvoiceId:cInv,createdPaymentId:cPay}));}
runTests().catch(console.error);
