export const landingPageContent = {
  fr: {
    nav: {
      features: 'Fonctionnalités',
      simulations: 'Simulations',
      audience: 'Pour qui ?',
      advantages: 'Avantages',
      pricing: 'Prix',
      mcpTools: 'MCP Tools',
      guide: 'Guide',
      peppol: 'Peppol',
      peppolGuide: 'Guide Peppol',
      login: 'Connexion',
      start: 'Démarrer',
    },
    hero: {
      badge: "Solution de gestion d'entreprise complète",
      subtitle: 'La révolution de la gestion automatisée : finance, projets & CRM',
      descriptionHighlight: 'Vous introduisez les données, CashPilot fait le reste.',
      descriptionBody: "Gestion financière, projets et CRM 100% automatisés pour la France, la Belgique et l'Afrique (OHADA).",
      mcpBanner: "Révolutionnaire dans le monde de la comptabilité et la finance d'entreprise : CashPilot est aussi un serveur MCP, qui offre 170+ outils à tout client MCP (ChatGPT, Claude, Gemini, Mistral, n8n, Gumloop), dont la gestion Projets, CRM (leads/tickets/SLA) et l'extraction IA de factures fournisseurs (PDF/image), pour une conversation en temps réel ou pour son intégration dans vos workflows d'automatisation (n8n, Zapier, Rube.app).",
      tags: {
        realtime: 'Temps réel (< 1 seconde)',
        regions: 'France • Belgique • OHADA',
        whatIf: 'Simulations What-If',
        reverseAccounting: 'Reverse Accounting',
        automated: '100% automatisé',
        mcp: 'Serveur MCP • 170+ outils IA',
        projectsCrm: 'Nouveau : Projets + CRM',
        security: 'MFA & GDPR',
      },
      primaryCta: 'Démarrer gratuitement',
      secondaryCta: 'Voir la démo',
      discover: 'Découvrir',
      stats: [
        { number: '< 1s', label: 'Génération écritures' },
        { number: '100%', label: 'Auto-comptabilité' },
        { number: '3 pays', label: 'FR • BE • OHADA' },
        { number: '2', label: 'Modules ajoutés' },
        { number: '0', label: 'Saisie manuelle' },
      ],
    },
    accounting: {
      badge: 'Solution tout-en-un multi-pays',
      title: 'Gestion financière & comptable automatisée',
      descriptionHighlight: 'Vous introduisez les données, CashPilot fait le reste.',
      descriptionBody: 'Comptabilité France 🇫🇷 • Belgique 🇧🇪 • OHADA 🌍',
      cards: [
        {
          title: 'Génération automatique',
          items: [
            'Créez une facture → écritures générées instantanément',
            'Enregistrez une dépense → écritures créées automatiquement',
            'Recevez un paiement → écriture bancaire automatique',
          ],
        },
        {
          title: 'Mises à jour temps réel',
          items: [
            'Diagnostic financier actualisé automatiquement',
            'Bilan et compte de résultat en direct (< 1 seconde)',
            'Synchronisation multi-onglets et multi-utilisateurs',
          ],
        },
        {
          title: 'Reverse Accounting',
          items: [
            "Supprimez un paiement → écriture d'annulation (OD)",
            'Supprimez une dépense → écritures inversées automatiquement',
            'Annulez une facture → contrepassation automatique',
          ],
        },
      ],
      countryTitle: 'Multi-pays & conformité totale',
      countryDescription: "Un système qui s'adapte aux normes comptables de votre pays",
      countries: [
        { flag: '🇫🇷', name: 'France', detail: 'PCG • Liasse fiscale' },
        { flag: '🇧🇪', name: 'Belgique', detail: 'PCMN • Déclaration TVA' },
        { flag: '🌍', name: 'OHADA', detail: '17 pays africains' },
      ],
      stats: [
        { number: '< 1s', label: 'Génération' },
        { number: '100%', label: 'Traçabilité' },
        { number: '0', label: 'Saisie manuelle' },
      ],
    },
    simulation: {
      badge: 'Simulations & projections financières',
      title: "Anticipez l'avenir de votre entreprise",
      description: 'Testez vos décisions avant de les prendre. Scénarios what-if, projections et aide à la décision.',
      cards: [
        {
          title: 'Simulation de croissance',
          question: "« Si j'augmente mes prix de 10%, quel sera l'impact sur ma trésorerie dans 6 mois ? »",
        },
        {
          title: "Planification d'embauche",
          question: "« Si j'embauche 2 personnes à 3000€/mois, puis-je tenir financièrement ? »",
        },
        {
          title: 'Investissement',
          question: "« Si j'achète un équipement à 50 000€, comment évoluera mon BFR ? »",
        },
        {
          title: 'Optimisation trésorerie',
          question: "« Si je négocie 60 jours de délai fournisseur au lieu de 30, quel impact sur le BFR ? »",
        },
        {
          title: 'Budget prévisionnel',
          question: "« Créer un budget pour l'année prochaine et comparer avec le réel »",
        },
      ],
      featureTitle: 'Fonctionnalités de simulation',
      features: [
        {
          title: 'Projections financières',
          description: "Prédisez l'évolution de votre trésorerie, CA et rentabilité sur 3, 6, 12 mois",
        },
        {
          title: 'Scénarios What-If',
          description: "Testez l'impact de vos décisions : embauches, investissements, prix...",
        },
        {
          title: 'Budget prévisionnel vs réel',
          description: 'Créez des budgets prévisionnels et comparez automatiquement avec le réel',
        },
        {
          title: 'Aide à la décision',
          description: 'Comparez plusieurs options et choisissez la meilleure stratégie',
        },
      ],
    },
    audience: {
      title: 'Conçu pour vous',
      description: "Quelle que soit votre activité, CashPilot s'adapte à vos besoins",
      cards: [
        { title: 'Freelances', description: 'Gestion complète de votre activité' },
        { title: 'PME/TPE', description: "Suite de gestion d'entreprise" },
        { title: 'Agences', description: 'Gestion projets et clients' },
        { title: 'Consultants', description: 'Suivi temps et facturation' },
        { title: 'Commerçants', description: 'Gestion stock et fournisseurs' },
        { title: 'Services', description: 'Facturation et projets' },
      ],
    },
    features: {
      title: 'Fonctionnalités principales',
      description: "Une suite complète d'outils pour gérer tous les aspects de votre entreprise",
      cards: [
        { title: 'Gestion clients', description: 'CRM Pro par société : comptes, leads, opportunités, activités, devis et tickets SLA' },
        { title: 'Projets & tâches', description: 'Pilotez vos projets, tâches, dépendances, sous-tâches, Gantt, Kanban, coûts et rentabilité' },
        { title: 'Suivi du temps', description: 'Feuilles de temps et chronomètre intégré' },
        { title: 'Facturation', description: 'Factures et devis professionnels en PDF' },
        { title: 'Comptabilité multi-pays', description: 'France, Belgique, OHADA - écritures automatiques en temps réel' },
        { title: 'Gestion stock', description: 'Inventaire avec scanner de codes-barres' },
        { title: 'Dépenses', description: 'Suivi et catégorisation des dépenses' },
        { title: 'Fournisseurs', description: 'Gestion fournisseurs + extraction IA de factures via MCP' },
        { title: 'Pilotage stratégique', description: 'Centre de pilotage unifié : ratios, benchmarks sectoriels, fiscalité multi-zones et valorisation' },
        { title: 'Rapports & analytics', description: 'Visualisations et exports PDF personnalisés' },
        { title: 'Simulations financières', description: "Scénarios what-if et projections pour anticiper l'avenir" },
        { title: 'Serveur MCP & API', description: '170+ outils MCP (finance + projets + CRM + extraction IA factures) + API REST pour agents IA et automations' },
        { title: 'MFA / 2FA (TOTP)', description: 'Authentification à deux facteurs via Google Authenticator ou Authy' },
        { title: 'Conformité RGPD', description: "Consentement cookies, export données, droit à l'oubli" },
        { title: 'Extraction IA factures', description: 'Upload PDF/image → extraction automatique par Gemini 2.0 Flash, aussi via MCP' },
        { title: 'Connexion bancaire', description: '3000+ banques via GoCardless Open Banking' },
        { title: 'Email & rappels auto', description: 'Envoi de factures et rappels de paiement automatiques' },
        { title: 'Factures récurrentes', description: 'Facturation automatique des abonnements et contrats' },
        { title: 'API REST & webhooks', description: 'API documentée + webhooks HMAC pour intégrations externes' },
        { title: 'Taux de change BCE', description: '33 devises avec taux officiels mis à jour automatiquement' },
        { title: 'Export Excel/CSV natif', description: 'Export en un clic depuis toutes les pages principales' },
      ],
    },
    pilotage: {
      badge: "Pilotage d'entreprise",
      title: 'Centre de pilotage stratégique',
      description: 'Un tableau de bord unifié avec 6 onglets pour piloter votre entreprise en temps réel : ratios financiers, benchmarks sectoriels, fiscalité multi-zones et valorisation.',
      cards: [
        { title: "Vue d'ensemble", description: 'KPIs temps réel (CA, EBITDA, résultat net, FCF, valorisation), graphiques de tendances et alertes financières automatiques' },
        { title: 'Analyse comptable', description: "Ratios de structure (indépendance financière, gearing) et d'activité (DSO, DPO, rotation stocks, cycle de conversion cash)" },
        { title: 'Analyse financière', description: 'Marges (brute, EBITDA, opérationnelle), rentabilité (ROE, ROA, ROCE), structure du capital et tendances' },
        { title: 'Fiscalité & valorisation', description: "IS multi-zones (France, Belgique, OHADA), crédits d'impôt, valorisation par multiples EBITDA + DCF, sensibilité WACC" },
        { title: 'Simulateur', description: "Scénarios what-if : testez l'impact de vos décisions sur la trésorerie, les marges et la valorisation" },
        { title: 'Audit IA', description: 'Score de santé comptable, détection d’anomalies par catégorie, recommandations et corrections automatiques' },
      ],
      featureTitle: 'Benchmarks sectoriels intégrés',
      features: [
        { title: '5 secteurs', description: 'SaaS, industrie, commerce, construction, services B2B — cibles adaptées' },
        { title: '3 zones géographiques', description: 'France, Belgique, zone OHADA (17 pays) — fiscalité et normes locales' },
        { title: '13 ratios comparés', description: 'DSO, DPO, gearing, ROE, ROA, ROCE, marges... vs cibles sectorielles' },
        { title: 'Scoring automatique', description: "Chaque ratio évalué : excellent, bon, moyen ou critique — en un coup d'œil" },
      ],
    },
    mcp: {
      badge: 'Serveur MCP natif',
      title: 'Connecté à tous vos agents IA',
      description: "CashPilot est un serveur MCP (Model Context Protocol) avec 170+ outils intégrés, incluant désormais des services dédiés Projets et CRM (leads/tickets/SLA), en plus de l'extraction IA de factures fournisseurs. Pilotez votre gestion financière par la voix ou le texte, depuis n'importe quel agent IA.",
      agents: [
        { name: 'Claude', company: 'Anthropic' },
        { name: 'ChatGPT', company: 'OpenAI' },
        { name: 'Gemini', company: 'Google' },
        { name: 'Mistral', company: 'Mistral AI' },
        { name: 'Rube.app', company: 'Automation' },
        { name: 'n8n', company: 'Workflow' },
        { name: 'Gunloop', company: 'Automation' },
        { name: 'Tout client MCP', company: 'Universel' },
      ],
      cards: [
        { title: 'Contrôle vocal & texte', description: 'Pilotez CashPilot depuis Claude, ChatGPT, Gemini ou Mistral par la voix ou le texte. Créez des factures, consultez vos finances, générez des rapports — en langage naturel.' },
        { title: 'Nouveaux services MCP Projets & CRM', description: 'Créez et suivez des projets, tâches, leads, tickets et politiques SLA directement depuis vos agents IA, en scope société strict.' },
        { title: '170+ outils MCP', description: 'Création de factures, recherche de clients, pilotage projets, opérations CRM, export comptable, résumé financier, extraction IA de factures fournisseurs — 170+ outils accessibles via le protocole MCP standard.' },
        { title: "Brique d'automatisation", description: 'Intégrez CashPilot dans vos pipelines : Rube.app, n8n, Gunloop, Zapier, Make. Votre gestion financière devient un composant de votre écosystème automatisé.' },
      ],
      exampleLabel: 'Exemple depuis un agent IA',
      exampleText: '« Extrais cette facture fournisseur et enregistre-la dans CashPilot »',
      exampleResult: 'Facture extraite par IA : Fournisseur ABC, 2 450€ TTC, 3 lignes. Enregistrée automatiquement.',
    },
    peppol: {
      badge: 'Peppol & e-invoicing',
      title: 'Facturation électronique via Peppol',
      description: 'Envoyez et recevez vos factures sur le réseau européen Peppol directement depuis CashPilot, grâce à Scrada, Access Point certifié belge. Conforme EN16931 & UBL 2.1.',
      cards: [
        { title: 'Configuration en 5 minutes', description: "Créez votre compte Scrada, générez une clé API, et collez vos identifiants dans CashPilot. Un clic pour tester la connexion — c'est prêt.", tag: 'Dès 2 €/mois' },
        { title: 'Envoi Peppol automatique', description: "CashPilot valide votre facture (13 règles EN16931), génère le XML UBL conforme, et l'envoie via Scrada sur le réseau Peppol. Suivi du statut en temps réel.", tag: 'UBL 2.1 / BIS Billing 3.0' },
        { title: 'Réception & vérification', description: "Recevez les factures entrantes via Peppol et vérifiez si vos clients sont enregistrés sur le réseau — en un clic depuis leur fiche.", tag: 'B2G & B2B' },
      ],
      imageAlt: 'Connexion CashPilot - Peppol via Scrada : configuration, forfaits et bénéfices',
      cta: 'Voir le guide complet',
    },
    advantages: {
      title: 'Pourquoi choisir CashPilot ?',
      description: 'Des avantages qui font la différence',
      items: [
        'Vous introduisez les données, CashPilot fait tout le reste automatiquement',
        'Multi-pays : France (PCG), Belgique (PCMN), OHADA (17 pays)',
        'Simulations financières : testez vos décisions avant de les prendre',
        'Génération instantanée des écritures comptables (< 1 seconde)',
        'Reverse accounting : annulations et corrections automatiques',
        'Tout-en-un : gestion, facturation, comptabilité, simulations',
        'Serveur MCP : 170+ outils (finance, projets, CRM) dont extraction IA de factures, depuis ChatGPT, Claude, Gemini, Mistral',
        'Sécurité renforcée : MFA/2FA, RGPD, 244 tests automatisés',
        'IA intégrée : extraction factures fournisseurs par Gemini 2.0 Flash',
        'Banque connectée : 3000+ banques, rapprochement auto, taux de change BCE',
      ],
    },
    cta: {
      title: "Prêt à transformer votre gestion d'entreprise ?",
      description: "Rejoignez des milliers d'entrepreneurs qui ont déjà choisi CashPilot",
      primary: 'Commencer maintenant',
      secondary: 'Contactez-nous',
      note: '✨ Essai gratuit • Sans carte de crédit • Installation en 2 minutes',
    },
    footer: {
      tagline: 'La solution complète pour votre entreprise',
      powered: 'Propulsé par DMG Management',
      contactTitle: 'Contact',
      linksTitle: 'Liens rapides',
      links: {
        about: 'À propos',
        features: 'Fonctionnalités',
        pricing: 'Tarifs',
        support: 'Support',
      },
      rights: '© 2026 CashPilot. Tous droits réservés.',
      builtBy: 'Développé avec ❤️ par',
    },
  },
  en: {
    nav: {
      features: 'Features',
      simulations: 'Simulations',
      audience: 'Who is it for?',
      advantages: 'Advantages',
      pricing: 'Pricing',
      mcpTools: 'MCP Tools',
      guide: 'Guide',
      peppol: 'Peppol',
      peppolGuide: 'Peppol Guide',
      login: 'Log in',
      start: 'Start',
    },
    hero: {
      badge: 'Complete business management platform',
      subtitle: 'The automated management revolution: finance, projects & CRM',
      descriptionHighlight: 'You enter the data, CashPilot does the rest.',
      descriptionBody: '100% automated finance, projects, and CRM for France, Belgium, and OHADA Africa.',
      mcpBanner: 'A breakthrough for accounting and business finance: CashPilot is also an MCP server that exposes 170+ tools to any MCP client (ChatGPT, Claude, Gemini, Mistral, n8n, Gumloop), including Projects, CRM (leads/tickets/SLA), and AI supplier-invoice extraction (PDF/image), for real-time conversations or integration into your automation workflows (n8n, Zapier, Rube.app).',
      tags: {
        realtime: 'Real time (< 1 second)',
        regions: 'France • Belgium • OHADA',
        whatIf: 'What-if simulations',
        reverseAccounting: 'Reverse accounting',
        automated: '100% automated',
        mcp: 'MCP server • 170+ AI tools',
        projectsCrm: 'New: Projects + CRM',
        security: 'MFA & GDPR',
      },
      primaryCta: 'Start for free',
      secondaryCta: 'See the demo',
      discover: 'Discover',
      stats: [
        { number: '< 1s', label: 'Journal entries' },
        { number: '100%', label: 'Auto-accounting' },
        { number: '3 countries', label: 'FR • BE • OHADA' },
        { number: '2', label: 'New modules' },
        { number: '0', label: 'Manual entry' },
      ],
    },
    accounting: {
      badge: 'All-in-one multi-country solution',
      title: 'Automated finance & accounting',
      descriptionHighlight: 'You enter the data, CashPilot does the rest.',
      descriptionBody: 'Accounting for France 🇫🇷 • Belgium 🇧🇪 • OHADA 🌍',
      cards: [
        {
          title: 'Automatic generation',
          items: [
            'Create an invoice → journal entries generated instantly',
            'Record an expense → entries created automatically',
            'Receive a payment → automatic bank entry',
          ],
        },
        {
          title: 'Real-time updates',
          items: [
            'Financial diagnostics updated automatically',
            'Live balance sheet and profit & loss (< 1 second)',
            'Multi-tab and multi-user synchronization',
          ],
        },
        {
          title: 'Reverse accounting',
          items: [
            'Delete a payment → reversal entry created automatically',
            'Delete an expense → entries reversed automatically',
            'Cancel an invoice → automatic reversal',
          ],
        },
      ],
      countryTitle: 'Multi-country and fully compliant',
      countryDescription: "A system that adapts to your country's accounting standards",
      countries: [
        { flag: '🇫🇷', name: 'France', detail: 'PCG • Tax package' },
        { flag: '🇧🇪', name: 'Belgium', detail: 'PCMN • VAT return' },
        { flag: '🌍', name: 'OHADA', detail: '17 African countries' },
      ],
      stats: [
        { number: '< 1s', label: 'Generation' },
        { number: '100%', label: 'Traceability' },
        { number: '0', label: 'Manual entry' },
      ],
    },
    simulation: {
      badge: 'Financial simulations & projections',
      title: 'Anticipate the future of your business',
      description: 'Test your decisions before you make them. What-if scenarios, projections, and decision support.',
      cards: [
        {
          title: 'Growth simulation',
          question: '"If I raise prices by 10%, what will be the impact on cash flow in six months?"',
        },
        {
          title: 'Hiring planning',
          question: '"If I hire 2 people at €3,000/month, can I sustain it financially?"',
        },
        {
          title: 'Investment',
          question: '"If I buy equipment for €50,000, how will my working capital evolve?"',
        },
        {
          title: 'Cash optimization',
          question: '"If I negotiate 60 supplier-payment days instead of 30, what is the impact on working capital?"',
        },
        {
          title: 'Budget planning',
          question: '"Create next year’s budget and compare it with actuals"',
        },
      ],
      featureTitle: 'Simulation features',
      features: [
        {
          title: 'Financial projections',
          description: 'Forecast cash flow, revenue, and profitability over 3, 6, and 12 months',
        },
        {
          title: 'What-if scenarios',
          description: 'Test the impact of your decisions: hiring, investments, pricing...',
        },
        {
          title: 'Budget vs actual',
          description: 'Build forward budgets and compare them automatically against actual performance',
        },
        {
          title: 'Decision support',
          description: 'Compare multiple options and choose the best strategy',
        },
      ],
    },
    audience: {
      title: 'Built for you',
      description: 'Whatever your business, CashPilot adapts to your needs',
      cards: [
        { title: 'Freelancers', description: 'Complete management for your activity' },
        { title: 'SMBs', description: 'Business management suite' },
        { title: 'Agencies', description: 'Project and client management' },
        { title: 'Consultants', description: 'Time tracking and invoicing' },
        { title: 'Retailers', description: 'Inventory and supplier management' },
        { title: 'Service firms', description: 'Invoicing and project delivery' },
      ],
    },
    features: {
      title: 'Core features',
      description: 'A complete suite to run every part of your business',
      cards: [
        { title: 'Client management', description: 'Company-scoped Pro CRM: accounts, leads, opportunities, activities, quotes, and SLA tickets' },
        { title: 'Projects & tasks', description: 'Manage projects, tasks, dependencies, subtasks, Gantt, Kanban, costs, and profitability' },
        { title: 'Time tracking', description: 'Timesheets and built-in timer' },
        { title: 'Invoicing', description: 'Professional invoices and quotes in PDF' },
        { title: 'Multi-country accounting', description: 'France, Belgium, OHADA - automatic real-time entries' },
        { title: 'Inventory management', description: 'Inventory with barcode scanner' },
        { title: 'Expenses', description: 'Expense tracking and categorization' },
        { title: 'Suppliers', description: 'Supplier management + AI invoice extraction through MCP' },
        { title: 'Strategic steering', description: 'Unified cockpit for ratios, sector benchmarks, multi-zone taxation, and valuation' },
        { title: 'Reports & analytics', description: 'Visual dashboards and custom PDF exports' },
        { title: 'Financial simulations', description: 'What-if scenarios and projections to anticipate the future' },
        { title: 'MCP server & API', description: '170+ MCP tools (finance + projects + CRM + AI invoice extraction) + REST API for AI agents and automations' },
        { title: 'MFA / 2FA (TOTP)', description: 'Two-factor authentication with Google Authenticator or Authy' },
        { title: 'GDPR compliance', description: 'Cookie consent, data export, and right to be forgotten' },
        { title: 'AI invoice extraction', description: 'Upload PDF/image → automatic extraction by Gemini 2.0 Flash, also via MCP' },
        { title: 'Bank connectivity', description: '3000+ banks through GoCardless Open Banking' },
        { title: 'Email & auto reminders', description: 'Automatic invoice sending and payment reminders' },
        { title: 'Recurring invoices', description: 'Automated billing for subscriptions and contracts' },
        { title: 'REST API & webhooks', description: 'Documented API + HMAC webhooks for external integrations' },
        { title: 'ECB exchange rates', description: '33 currencies with automatically updated official rates' },
        { title: 'Native Excel/CSV export', description: 'One-click export from all core pages' },
      ],
    },
    pilotage: {
      badge: 'Business steering',
      title: 'Strategic steering cockpit',
      description: 'A unified dashboard with six tabs to steer your business in real time: financial ratios, sector benchmarks, multi-zone taxation, and valuation.',
      cards: [
        { title: 'Overview', description: 'Real-time KPIs (revenue, EBITDA, net income, FCF, valuation), trend charts, and financial alerts' },
        { title: 'Accounting analysis', description: 'Structural ratios (financial independence, gearing) and activity ratios (DSO, DPO, stock turns, cash conversion cycle)' },
        { title: 'Financial analysis', description: 'Margins (gross, EBITDA, operating), profitability (ROE, ROA, ROCE), capital structure, and trends' },
        { title: 'Tax & valuation', description: 'Corporate tax across regions (France, Belgium, OHADA), tax credits, EBITDA multiples + DCF valuation, WACC sensitivity' },
        { title: 'Simulator', description: 'What-if scenarios: test the impact of decisions on cash flow, margins, and valuation' },
        { title: 'AI audit', description: 'Accounting-health score, anomaly detection by category, recommendations, and automated corrections' },
      ],
      featureTitle: 'Built-in sector benchmarks',
      features: [
        { title: '5 sectors', description: 'SaaS, industry, retail, construction, B2B services — tailored targets' },
        { title: '3 geographies', description: 'France, Belgium, OHADA area (17 countries) — local tax and accounting rules' },
        { title: '13 compared ratios', description: 'DSO, DPO, gearing, ROE, ROA, ROCE, margins... against sector targets' },
        { title: 'Automatic scoring', description: 'Every ratio graded as excellent, good, average, or critical — at a glance' },
      ],
    },
    mcp: {
      badge: 'Native MCP server',
      title: 'Connected to all your AI agents',
      description: 'CashPilot is an MCP (Model Context Protocol) server with 170+ built-in tools, now including dedicated Projects and CRM services (leads/tickets/SLA), plus AI supplier-invoice extraction. Run your finance operations by voice or text from any AI agent.',
      agents: [
        { name: 'Claude', company: 'Anthropic' },
        { name: 'ChatGPT', company: 'OpenAI' },
        { name: 'Gemini', company: 'Google' },
        { name: 'Mistral', company: 'Mistral AI' },
        { name: 'Rube.app', company: 'Automation' },
        { name: 'n8n', company: 'Workflow' },
        { name: 'Gunloop', company: 'Automation' },
        { name: 'Any MCP client', company: 'Universal' },
      ],
      cards: [
        { title: 'Voice & text control', description: 'Operate CashPilot from Claude, ChatGPT, Gemini, or Mistral by voice or text. Create invoices, inspect finances, and generate reports in natural language.' },
        { title: 'New MCP services: Projects & CRM', description: 'Create and track projects, tasks, leads, tickets, and SLA policies directly from AI agents with strict company scope.' },
        { title: '170+ MCP tools', description: 'Invoice creation, client lookup, project management, CRM operations, accounting export, financial summaries, AI supplier-invoice extraction — 170+ tools available through the standard MCP protocol.' },
        { title: 'Automation building block', description: 'Integrate CashPilot into your pipelines: Rube.app, n8n, Gunloop, Zapier, Make. Your finance operations become a component of your automation stack.' },
      ],
      exampleLabel: 'Example from an AI agent',
      exampleText: '"Extract this supplier invoice and save it to CashPilot"',
      exampleResult: 'Invoice extracted by AI: Supplier ABC, €2,450 incl. VAT, 3 lines. Saved automatically.',
    },
    peppol: {
      badge: 'Peppol & e-invoicing',
      title: 'Electronic invoicing through Peppol',
      description: 'Send and receive invoices on the European Peppol network directly from CashPilot, thanks to Scrada, a certified Belgian access point. Compliant with EN16931 & UBL 2.1.',
      cards: [
        { title: 'Setup in 5 minutes', description: 'Create your Scrada account, generate an API key, and paste your credentials into CashPilot. One click to test the connection — you are ready.', tag: 'From €2/month' },
        { title: 'Automatic Peppol sending', description: 'CashPilot validates your invoice (13 EN16931 rules), generates compliant UBL XML, and sends it through Scrada on the Peppol network. Live status tracking included.', tag: 'UBL 2.1 / BIS Billing 3.0' },
        { title: 'Receiving & verification', description: 'Receive incoming invoices through Peppol and verify whether your clients are registered on the network — directly from their profile in one click.', tag: 'B2G & B2B' },
      ],
      imageAlt: 'CashPilot - Peppol via Scrada connection: setup, plans, and benefits',
      cta: 'See the full guide',
    },
    advantages: {
      title: 'Why choose CashPilot?',
      description: 'Advantages that truly stand out',
      items: [
        'You enter the data, CashPilot handles everything else automatically',
        'Multi-country: France (PCG), Belgium (PCMN), OHADA (17 countries)',
        'Financial simulations: test decisions before you make them',
        'Instant journal-entry generation (< 1 second)',
        'Reverse accounting: automatic cancellations and corrections',
        'All-in-one: operations, invoicing, accounting, simulations',
        'MCP server: 170+ tools (finance, projects, CRM) including AI invoice extraction from ChatGPT, Claude, Gemini, and Mistral',
        'Stronger security: MFA/2FA, GDPR, 244 automated tests',
        'Built-in AI: supplier-invoice extraction with Gemini 2.0 Flash',
        'Connected banking: 3000+ banks, automatic matching, ECB exchange rates',
      ],
    },
    cta: {
      title: 'Ready to transform how you run your business?',
      description: 'Join thousands of entrepreneurs who already chose CashPilot',
      primary: 'Start now',
      secondary: 'Contact us',
      note: '✨ Free trial • No credit card • Setup in 2 minutes',
    },
    footer: {
      tagline: 'The complete solution for your business',
      powered: 'Powered by DMG Management',
      contactTitle: 'Contact',
      linksTitle: 'Quick links',
      links: {
        about: 'About',
        features: 'Features',
        pricing: 'Pricing',
        support: 'Support',
      },
      rights: '© 2026 CashPilot. All rights reserved.',
      builtBy: 'Built with ❤️ by',
    },
  },
  nl: {
    nav: {
      features: 'Functies',
      simulations: 'Simulaties',
      audience: 'Voor wie?',
      advantages: 'Voordelen',
      pricing: 'Prijzen',
      mcpTools: 'MCP Tools',
      guide: 'Gids',
      peppol: 'Peppol',
      peppolGuide: 'Peppol-gids',
      login: 'Inloggen',
      start: 'Starten',
    },
    hero: {
      badge: 'Volledig platform voor bedrijfsbeheer',
      subtitle: 'De revolutie van geautomatiseerd beheer: finance, projecten & CRM',
      descriptionHighlight: 'U voert de gegevens in, CashPilot doet de rest.',
      descriptionBody: '100% geautomatiseerde financiële opvolging, projectbeheer en CRM voor Frankrijk, België en OHADA-Afrika.',
      mcpBanner: 'Een doorbraak in boekhouding en bedrijfsfinanciën: CashPilot is ook een MCP-server die 170+ tools aanbiedt aan elke MCP-client (ChatGPT, Claude, Gemini, Mistral, n8n, Gumloop), waaronder projectbeheer, CRM (leads/tickets/SLA) en AI-extractie van leveranciersfacturen (pdf/afbeelding), voor realtime gesprekken of integratie in uw automatiseringsworkflows (n8n, Zapier, Rube.app).',
      tags: {
        realtime: 'Realtime (< 1 seconde)',
        regions: 'Frankrijk • België • OHADA',
        whatIf: 'What-if-simulaties',
        reverseAccounting: 'Reverse accounting',
        automated: '100% geautomatiseerd',
        mcp: 'MCP-server • 170+ AI-tools',
        projectsCrm: 'Nieuw: Projecten + CRM',
        security: 'MFA & GDPR',
      },
      primaryCta: 'Gratis starten',
      secondaryCta: 'Bekijk de demo',
      discover: 'Ontdekken',
      stats: [
        { number: '< 1s', label: 'Boekingen' },
        { number: '100%', label: 'Auto-boekhouding' },
        { number: '3 landen', label: 'FR • BE • OHADA' },
        { number: '2', label: 'Nieuwe modules' },
        { number: '0', label: 'Handmatige invoer' },
      ],
    },
    accounting: {
      badge: 'Alles-in-één oplossing voor meerdere landen',
      title: 'Geautomatiseerde financiële & boekhoudkundige opvolging',
      descriptionHighlight: 'U voert de gegevens in, CashPilot doet de rest.',
      descriptionBody: 'Boekhouding voor Frankrijk 🇫🇷 • België 🇧🇪 • OHADA 🌍',
      cards: [
        {
          title: 'Automatische generatie',
          items: [
            'Maak een factuur aan → boekingen direct gegenereerd',
            'Registreer een uitgave → boekingen automatisch aangemaakt',
            'Ontvang een betaling → automatische bankboeking',
          ],
        },
        {
          title: 'Realtime updates',
          items: [
            'Financiële diagnose automatisch bijgewerkt',
            'Balans en resultatenrekening live (< 1 seconde)',
            'Synchronisatie over meerdere tabs en gebruikers',
          ],
        },
        {
          title: 'Reverse accounting',
          items: [
            'Verwijder een betaling → tegenboeking automatisch aangemaakt',
            'Verwijder een uitgave → boekingen automatisch teruggedraaid',
            'Annuleer een factuur → automatische tegenboeking',
          ],
        },
      ],
      countryTitle: 'Meerdere landen & volledige compliance',
      countryDescription: 'Een systeem dat zich aanpast aan de boekhoudnormen van uw land',
      countries: [
        { flag: '🇫🇷', name: 'Frankrijk', detail: 'PCG • Fiscale bundel' },
        { flag: '🇧🇪', name: 'België', detail: 'PCMN • Btw-aangifte' },
        { flag: '🌍', name: 'OHADA', detail: '17 Afrikaanse landen' },
      ],
      stats: [
        { number: '< 1s', label: 'Generatie' },
        { number: '100%', label: 'Traceerbaarheid' },
        { number: '0', label: 'Handmatige invoer' },
      ],
    },
    simulation: {
      badge: 'Financiële simulaties & projecties',
      title: 'Anticipeer op de toekomst van uw onderneming',
      description: 'Test uw beslissingen vóór u ze neemt. What-if-scenario’s, projecties en beslissingsondersteuning.',
      cards: [
        {
          title: 'Groeisimulatie',
          question: '"Als ik mijn prijzen met 10% verhoog, wat is dan het effect op mijn cashflow binnen zes maanden?"',
        },
        {
          title: 'Personeelsplanning',
          question: '"Als ik 2 mensen aanwerf aan €3.000 per maand, kan ik dat financieel dragen?"',
        },
        {
          title: 'Investering',
          question: '"Als ik een uitrusting koop voor €50.000, hoe evolueert mijn werkkapitaal?"',
        },
        {
          title: 'Cashoptimalisatie',
          question: '"Als ik 60 dagen leverancierskrediet onderhandel in plaats van 30, wat is de impact op het werkkapitaal?"',
        },
        {
          title: 'Budgetplanning',
          question: '"Maak een budget voor volgend jaar en vergelijk het met de realiteit"',
        },
      ],
      featureTitle: 'Simulatiefuncties',
      features: [
        {
          title: 'Financiële projecties',
          description: 'Voorspel cashflow, omzet en rendabiliteit over 3, 6 en 12 maanden',
        },
        {
          title: 'What-if-scenario’s',
          description: 'Test de impact van uw beslissingen: aanwervingen, investeringen, prijzen...',
        },
        {
          title: 'Budget vs realiteit',
          description: 'Maak vooruitblikkende budgetten en vergelijk ze automatisch met de realiteit',
        },
        {
          title: 'Beslissingsondersteuning',
          description: 'Vergelijk meerdere opties en kies de beste strategie',
        },
      ],
    },
    audience: {
      title: 'Ontworpen voor u',
      description: 'Welke activiteit u ook heeft, CashPilot past zich aan uw noden aan',
      cards: [
        { title: 'Freelancers', description: 'Volledig beheer van uw activiteit' },
        { title: "KMO's", description: 'Suite voor bedrijfsbeheer' },
        { title: 'Agentschappen', description: 'Beheer van projecten en klanten' },
        { title: 'Consultants', description: 'Tijdsregistratie en facturatie' },
        { title: 'Handelaars', description: 'Voorraad- en leveranciersbeheer' },
        { title: 'Dienstverleners', description: 'Facturatie en projecten' },
      ],
    },
    features: {
      title: 'Belangrijkste functies',
      description: 'Een volledige suite om elk onderdeel van uw onderneming te beheren',
      cards: [
        { title: 'Klantenbeheer', description: 'Pro CRM per vennootschap: accounts, leads, opportuniteiten, activiteiten, offertes en SLA-tickets' },
        { title: 'Projecten & taken', description: 'Beheer projecten, taken, afhankelijkheden, subtaken, Gantt, Kanban, kosten en rendabiliteit' },
        { title: 'Tijdsregistratie', description: 'Urenstaten en ingebouwde timer' },
        { title: 'Facturatie', description: 'Professionele facturen en offertes in pdf' },
        { title: 'Boekhouding voor meerdere landen', description: 'Frankrijk, België, OHADA - automatische realtime boekingen' },
        { title: 'Voorraadbeheer', description: 'Inventaris met barcodescanner' },
        { title: 'Uitgaven', description: 'Opvolging en categorisatie van uitgaven' },
        { title: 'Leveranciers', description: 'Leveranciersbeheer + AI-factuurextractie via MCP' },
        { title: 'Strategische sturing', description: 'Geünificeerd cockpit voor ratio’s, sectorbenchmarks, fiscaliteit in meerdere zones en waardering' },
        { title: 'Rapporten & analyses', description: 'Visuele dashboards en aangepaste pdf-exporten' },
        { title: 'Financiële simulaties', description: 'What-if-scenario’s en projecties om vooruit te kijken' },
        { title: 'MCP-server & API', description: '170+ MCP-tools (finance + projecten + CRM + AI-factuurextractie) + REST API voor AI-agents en automatiseringen' },
        { title: 'MFA / 2FA (TOTP)', description: 'Twee-factor-authenticatie via Google Authenticator of Authy' },
        { title: 'GDPR-compliance', description: 'Cookieconsent, data-export en recht op vergetelheid' },
        { title: 'AI-factuurextractie', description: 'Upload pdf/afbeelding → automatische extractie door Gemini 2.0 Flash, ook via MCP' },
        { title: 'Bankkoppeling', description: '3000+ banken via GoCardless Open Banking' },
        { title: 'E-mail & automatische herinneringen', description: 'Automatisch verzenden van facturen en betalingsherinneringen' },
        { title: 'Terugkerende facturen', description: 'Automatische facturatie van abonnementen en contracten' },
        { title: 'REST API & webhooks', description: 'Gedocumenteerde API + HMAC-webhooks voor externe integraties' },
        { title: 'ECB-wisselkoersen', description: '33 valuta met automatisch bijgewerkte officiële koersen' },
        { title: 'Native Excel/CSV-export', description: 'Export met één klik vanaf alle hoofdschermen' },
      ],
    },
    pilotage: {
      badge: 'Bedrijfssturing',
      title: 'Strategische stuurcockpit',
      description: 'Een geünificeerd dashboard met zes tabs om uw onderneming realtime te sturen: financiële ratio’s, sectorbenchmarks, fiscaliteit in meerdere zones en waardering.',
      cards: [
        { title: 'Overzicht', description: 'Realtime KPI’s (omzet, EBITDA, nettoresultaat, FCF, waardering), trendgrafieken en automatische financiële waarschuwingen' },
        { title: 'Boekhoudanalyse', description: 'Structuurratio’s (financiële onafhankelijkheid, gearing) en activiteitsratio’s (DSO, DPO, voorraadrotatie, cash conversion cycle)' },
        { title: 'Financiële analyse', description: 'Marges (bruto, EBITDA, operationeel), rendabiliteit (ROE, ROA, ROCE), kapitaalstructuur en trends' },
        { title: 'Fiscaliteit & waardering', description: 'Vennootschapsbelasting per regio (Frankrijk, België, OHADA), belastingkredieten, EBITDA-multiples + DCF-waardering, WACC-sensitiviteit' },
        { title: 'Simulator', description: 'What-if-scenario’s: test de impact van beslissingen op cashflow, marges en waardering' },
        { title: 'AI-audit', description: 'Score voor boekhoudgezondheid, anomaliedetectie per categorie, aanbevelingen en automatische correcties' },
      ],
      featureTitle: 'Geïntegreerde sectorbenchmarks',
      features: [
        { title: '5 sectoren', description: 'SaaS, industrie, handel, bouw, B2B-diensten — aangepaste doelwaarden' },
        { title: '3 geografische zones', description: 'Frankrijk, België, OHADA-zone (17 landen) — lokale fiscale en boekhoudregels' },
        { title: '13 vergeleken ratio’s', description: 'DSO, DPO, gearing, ROE, ROA, ROCE, marges... tegenover sectordoelen' },
        { title: 'Automatische scoring', description: 'Elke ratio beoordeeld als uitstekend, goed, gemiddeld of kritisch — in één oogopslag' },
      ],
    },
    mcp: {
      badge: 'Native MCP-server',
      title: 'Verbonden met al uw AI-agents',
      description: 'CashPilot is een MCP-server (Model Context Protocol) met 170+ ingebouwde tools, nu ook met dedicated services voor Projecten en CRM (leads/tickets/SLA), plus AI-extractie van leveranciersfacturen. Stuur uw financiën via stem of tekst vanuit eender welke AI-agent.',
      agents: [
        { name: 'Claude', company: 'Anthropic' },
        { name: 'ChatGPT', company: 'OpenAI' },
        { name: 'Gemini', company: 'Google' },
        { name: 'Mistral', company: 'Mistral AI' },
        { name: 'Rube.app', company: 'Automatisering' },
        { name: 'n8n', company: 'Workflow' },
        { name: 'Gunloop', company: 'Automatisering' },
        { name: 'Elke MCP-client', company: 'Universeel' },
      ],
      cards: [
        { title: 'Spraak- & tekststuring', description: 'Bedien CashPilot vanuit Claude, ChatGPT, Gemini of Mistral via spraak of tekst. Maak facturen, raadpleeg uw financiën en genereer rapporten in natuurlijke taal.' },
        { title: 'Nieuwe MCP-services: Projecten & CRM', description: 'Maak en volg projecten, taken, leads, tickets en SLA-beleid rechtstreeks vanuit AI-agents met strikte company-scope.' },
        { title: '170+ MCP-tools', description: 'Facturen aanmaken, klanten opzoeken, projectbeheer, CRM-operaties, boekhoudkundige exporten, financiële samenvattingen, AI-extractie van leveranciersfacturen — 170+ tools toegankelijk via het standaard MCP-protocol.' },
        { title: 'Automatiseringsbouwsteen', description: 'Integreer CashPilot in uw pipelines: Rube.app, n8n, Gunloop, Zapier, Make. Uw financiële beheer wordt een component van uw automatiseringsstack.' },
      ],
      exampleLabel: 'Voorbeeld vanuit een AI-agent',
      exampleText: '"Haal deze leveranciersfactuur op en sla ze op in CashPilot"',
      exampleResult: 'Factuur door AI geëxtraheerd: Leverancier ABC, €2.450 incl. btw, 3 lijnen. Automatisch opgeslagen.',
    },
    peppol: {
      badge: 'Peppol & e-invoicing',
      title: 'Elektronische facturatie via Peppol',
      description: 'Verzend en ontvang uw facturen op het Europese Peppol-netwerk rechtstreeks vanuit CashPilot, dankzij Scrada, een gecertificeerd Belgisch access point. Conform EN16931 & UBL 2.1.',
      cards: [
        { title: 'Opzet in 5 minuten', description: 'Maak uw Scrada-account aan, genereer een API-sleutel en plak uw gegevens in CashPilot. Eén klik om de verbinding te testen — klaar.', tag: 'Vanaf €2/maand' },
        { title: 'Automatisch Peppol-verzenden', description: 'CashPilot valideert uw factuur (13 EN16931-regels), genereert conforme UBL-XML en verstuurt die via Scrada op het Peppol-netwerk. Inclusief realtime statusopvolging.', tag: 'UBL 2.1 / BIS Billing 3.0' },
        { title: 'Ontvangst & verificatie', description: 'Ontvang inkomende facturen via Peppol en controleer of uw klanten op het netwerk geregistreerd zijn — met één klik vanuit hun fiche.', tag: 'B2G & B2B' },
      ],
      imageAlt: 'CashPilot - Peppol via Scrada: configuratie, formules en voordelen',
      cta: 'Bekijk de volledige gids',
    },
    advantages: {
      title: 'Waarom kiezen voor CashPilot?',
      description: 'Voordelen die echt het verschil maken',
      items: [
        'U voert de gegevens in, CashPilot doet automatisch de rest',
        'Meerdere landen: Frankrijk (PCG), België (PCMN), OHADA (17 landen)',
        'Financiële simulaties: test uw beslissingen vóór u ze neemt',
        'Onmiddellijke generatie van boekingen (< 1 seconde)',
        'Reverse accounting: automatische annulaties en correcties',
        'Alles-in-één: beheer, facturatie, boekhouding, simulaties',
        'MCP-server: 170+ tools (finance, projecten, CRM) waaronder AI-factuurextractie vanuit ChatGPT, Claude, Gemini en Mistral',
        'Sterkere beveiliging: MFA/2FA, GDPR, 244 geautomatiseerde tests',
        'Ingebouwde AI: leveranciersfactuurextractie met Gemini 2.0 Flash',
        'Verbonden bankieren: 3000+ banken, automatische matching, ECB-koersen',
      ],
    },
    cta: {
      title: 'Klaar om uw bedrijfsbeheer te transformeren?',
      description: 'Sluit u aan bij duizenden ondernemers die al voor CashPilot kozen',
      primary: 'Nu starten',
      secondary: 'Contacteer ons',
      note: '✨ Gratis proefperiode • Geen kredietkaart • Installatie in 2 minuten',
    },
    footer: {
      tagline: 'De complete oplossing voor uw onderneming',
      powered: 'Aangedreven door DMG Management',
      contactTitle: 'Contact',
      linksTitle: 'Snelle links',
      links: {
        about: 'Over',
        features: 'Functies',
        pricing: 'Prijzen',
        support: 'Support',
      },
      rights: '© 2026 CashPilot. Alle rechten voorbehouden.',
      builtBy: 'Ontwikkeld met ❤️ door',
    },
  },
};
