
import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Label } from '@/components/ui/label';
import { FileText, Download, Loader2 } from 'lucide-react';
import html2pdf from 'html2pdf.js';
import { useToast } from '@/components/ui/use-toast';

const ReportGenerator = () => {
  const [reportType, setReportType] = useState('summary');
  const [generating, setGenerating] = useState(false);
  const { toast } = useToast();

  const handleDownload = async () => {
    setGenerating(true);
    // Determine content based on report type - mocking content for demo
    const element = document.createElement('div');
    element.innerHTML = `
      <div style="padding: 20px; font-family: sans-serif; color: #000;">
        <h1 style="color: #2563eb;">CashPilot ${reportType.charAt(0).toUpperCase() + reportType.slice(1)} Report</h1>
        <p>Date: ${new Date().toLocaleDateString()}</p>
        <hr />
        <h3>Executive Summary</h3>
        <p>This is an automated report generated by CashPilot.</p>
        <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
           <tr style="background: #f3f4f6;">
             <th style="padding: 10px; border: 1px solid #ccc;">Metric</th>
             <th style="padding: 10px; border: 1px solid #ccc;">Value</th>
           </tr>
           <tr>
             <td style="padding: 10px; border: 1px solid #ccc;">Total Revenue</td>
             <td style="padding: 10px; border: 1px solid #ccc;">$124,500.00</td>
           </tr>
           <tr>
             <td style="padding: 10px; border: 1px solid #ccc;">Active Projects</td>
             <td style="padding: 10px; border: 1px solid #ccc;">14</td>
           </tr>
        </table>
      </div>
    `;

    const opt = {
      margin: 1,
      filename: `cashpilot-report-${Date.now()}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
    };

    try {
      await html2pdf().set(opt).from(element).save();
      toast({ title: "Success", description: "Report downloaded successfully." });
    } catch (err) {
      console.error(err);
      toast({ title: "Error", description: "Failed to generate report.", variant: "destructive" });
    } finally {
      setGenerating(false);
    }
  };

  return (
    <Card className="bg-gray-900 border-gray-800 text-white max-w-md mx-auto mt-8">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <FileText className="text-orange-400" /> Report Generator
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label>Report Type</Label>
          <Select value={reportType} onValueChange={setReportType}>
            <SelectTrigger className="bg-gray-800 border-gray-700">
              <SelectValue />
            </SelectTrigger>
            <SelectContent className="bg-gray-800 border-gray-700 text-white">
              <SelectItem value="summary">Financial Summary</SelectItem>
              <SelectItem value="invoices">Invoice Status</SelectItem>
              <SelectItem value="projects">Project Performance</SelectItem>
            </SelectContent>
          </Select>
        </div>

        <Button onClick={handleDownload} disabled={generating} className="w-full bg-orange-500 hover:bg-orange-600">
          {generating ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Download className="mr-2 h-4 w-4" />}
          Download PDF
        </Button>
      </CardContent>
    </Card>
  );
};

export default ReportGenerator;
