-- HR P0-004: RLS policies for HR modules
-- Applied to Supabase production via MCP apply_migration.
-- Local file created to match remote schema_migrations version.
-- See local equivalents in git history for full SQL content.
