-- ============================================================================
-- SYSCOHADA Seed Data
-- Plan comptable OHADA pour CI (Cote d'Ivoire) et CM (Cameroun)
-- Regles fiscales et templates de rapports
-- ============================================================================

-- =====================================================================
-- A. PLAN COMPTABLE SYSCOHADA — COTE D'IVOIRE (CI)
-- =====================================================================

INSERT INTO public.syscohada_chart_templates (country_code, account_class, account_code, account_name, account_type, parent_code) VALUES

-- Classe 1 : Comptes de ressources durables
('CI', 1, '10', 'Capital', 'equity', NULL),
('CI', 1, '101', 'Capital social', 'equity', '10'),
('CI', 1, '1011', 'Capital souscrit, non appele', 'equity', '101'),
('CI', 1, '1012', 'Capital souscrit, appele, non verse', 'equity', '101'),
('CI', 1, '1013', 'Capital souscrit, appele, verse', 'equity', '101'),
('CI', 1, '11', 'Reserves', 'equity', NULL),
('CI', 1, '111', 'Reserve legale', 'equity', '11'),
('CI', 1, '112', 'Reserves statutaires ou contractuelles', 'equity', '11'),
('CI', 1, '118', 'Autres reserves', 'equity', '11'),
('CI', 1, '12', 'Report a nouveau', 'equity', NULL),
('CI', 1, '121', 'Report a nouveau crediteur', 'equity', '12'),
('CI', 1, '129', 'Report a nouveau debiteur', 'equity', '12'),
('CI', 1, '13', 'Resultat net de l''exercice', 'equity', NULL),
('CI', 1, '131', 'Resultat net : benefice', 'equity', '13'),
('CI', 1, '139', 'Resultat net : perte', 'equity', '13'),
('CI', 1, '14', 'Subventions d''investissement', 'equity', NULL),
('CI', 1, '15', 'Provisions reglementees et fonds assimiles', 'equity', NULL),
('CI', 1, '16', 'Emprunts et dettes assimilees', 'liability', NULL),
('CI', 1, '161', 'Emprunts obligataires', 'liability', '16'),
('CI', 1, '162', 'Emprunts et dettes aupres des etablissements de credit', 'liability', '16'),
('CI', 1, '17', 'Dettes de credit-bail et contrats assimiles', 'liability', NULL),
('CI', 1, '18', 'Dettes liees a des participations', 'liability', NULL),
('CI', 1, '19', 'Provisions financieres pour risques et charges', 'liability', NULL),

-- Classe 2 : Comptes d'actif immobilise
('CI', 2, '20', 'Charges immobilisees', 'asset', NULL),
('CI', 2, '201', 'Frais d''etablissement', 'asset', '20'),
('CI', 2, '202', 'Charges a repartir sur plusieurs exercices', 'asset', '20'),
('CI', 2, '21', 'Immobilisations incorporelles', 'asset', NULL),
('CI', 2, '211', 'Frais de recherche et de developpement', 'asset', '21'),
('CI', 2, '212', 'Brevets, licences, concessions', 'asset', '21'),
('CI', 2, '213', 'Logiciels et sites internet', 'asset', '21'),
('CI', 2, '214', 'Marques', 'asset', '21'),
('CI', 2, '215', 'Fonds commercial', 'asset', '21'),
('CI', 2, '22', 'Terrains', 'asset', NULL),
('CI', 2, '221', 'Terrains agricoles et forestiers', 'asset', '22'),
('CI', 2, '222', 'Terrains nus', 'asset', '22'),
('CI', 2, '223', 'Terrains batis', 'asset', '22'),
('CI', 2, '23', 'Batiments, installations techniques et agencements', 'asset', NULL),
('CI', 2, '231', 'Batiments industriels', 'asset', '23'),
('CI', 2, '232', 'Batiments commerciaux', 'asset', '23'),
('CI', 2, '233', 'Batiments administratifs', 'asset', '23'),
('CI', 2, '24', 'Materiel', 'asset', NULL),
('CI', 2, '241', 'Materiel et outillage industriel', 'asset', '24'),
('CI', 2, '242', 'Materiel et outillage agricole', 'asset', '24'),
('CI', 2, '244', 'Materiel et mobilier de bureau', 'asset', '24'),
('CI', 2, '245', 'Materiel de transport', 'asset', '24'),
('CI', 2, '246', 'Materiel informatique', 'asset', '24'),
('CI', 2, '25', 'Avances et acomptes verses sur immobilisations', 'asset', NULL),
('CI', 2, '26', 'Titres de participation', 'asset', NULL),
('CI', 2, '27', 'Autres immobilisations financieres', 'asset', NULL),
('CI', 2, '28', 'Amortissements', 'asset', NULL),
('CI', 2, '281', 'Amortissements des immobilisations incorporelles', 'asset', '28'),
('CI', 2, '283', 'Amortissements des batiments', 'asset', '28'),
('CI', 2, '284', 'Amortissements du materiel', 'asset', '28'),
('CI', 2, '29', 'Provisions pour depreciation', 'asset', NULL),

-- Classe 3 : Comptes de stocks
('CI', 3, '31', 'Marchandises', 'asset', NULL),
('CI', 3, '32', 'Matieres premieres et fournitures liees', 'asset', NULL),
('CI', 3, '33', 'Autres approvisionnements', 'asset', NULL),
('CI', 3, '34', 'Produits en cours', 'asset', NULL),
('CI', 3, '35', 'Services en cours', 'asset', NULL),
('CI', 3, '36', 'Produits finis', 'asset', NULL),
('CI', 3, '37', 'Produits intermediaires et residuels', 'asset', NULL),
('CI', 3, '38', 'Stocks en cours de route, en consignation', 'asset', NULL),
('CI', 3, '39', 'Depreciations des stocks', 'asset', NULL),

-- Classe 4 : Comptes de tiers
('CI', 4, '40', 'Fournisseurs et comptes rattaches', 'liability', NULL),
('CI', 4, '401', 'Fournisseurs, dettes en compte', 'liability', '40'),
('CI', 4, '402', 'Fournisseurs, effets a payer', 'liability', '40'),
('CI', 4, '408', 'Fournisseurs, factures non parvenues', 'liability', '40'),
('CI', 4, '41', 'Clients et comptes rattaches', 'asset', NULL),
('CI', 4, '411', 'Clients', 'asset', '41'),
('CI', 4, '412', 'Clients, effets a recevoir', 'asset', '41'),
('CI', 4, '416', 'Clients douteux', 'asset', '41'),
('CI', 4, '418', 'Clients, produits a recevoir', 'asset', '41'),
('CI', 4, '42', 'Personnel', 'liability', NULL),
('CI', 4, '421', 'Personnel, avances et acomptes', 'asset', '42'),
('CI', 4, '422', 'Personnel, remunerations dues', 'liability', '42'),
('CI', 4, '43', 'Organismes sociaux', 'liability', NULL),
('CI', 4, '431', 'Securite sociale', 'liability', '43'),
('CI', 4, '432', 'Caisses de retraite', 'liability', '43'),
('CI', 4, '44', 'Etat et collectivites publiques', 'liability', NULL),
('CI', 4, '441', 'Etat, impot sur les benefices', 'liability', '44'),
('CI', 4, '443', 'Etat, TVA facturee', 'liability', '44'),
('CI', 4, '445', 'Etat, TVA recuperable', 'asset', '44'),
('CI', 4, '447', 'Etat, impots retenus a la source', 'liability', '44'),
('CI', 4, '449', 'Etat, credit de TVA', 'asset', '44'),
('CI', 4, '46', 'Associes et groupe', 'liability', NULL),
('CI', 4, '47', 'Debiteurs et crediteurs divers', 'liability', NULL),
('CI', 4, '48', 'Creances et dettes hors activite ordinaire', 'liability', NULL),
('CI', 4, '49', 'Depreciations et provisions pour risques (tiers)', 'liability', NULL),

-- Classe 5 : Comptes de tresorerie
('CI', 5, '50', 'Titres de placement', 'asset', NULL),
('CI', 5, '51', 'Valeurs a encaisser', 'asset', NULL),
('CI', 5, '52', 'Banques', 'asset', NULL),
('CI', 5, '521', 'Banques locales', 'asset', '52'),
('CI', 5, '522', 'Banques autres etats UEMOA', 'asset', '52'),
('CI', 5, '523', 'Banques hors UEMOA', 'asset', '52'),
('CI', 5, '53', 'Etablissements financiers et assimiles', 'asset', NULL),
('CI', 5, '54', 'Instruments de tresorerie', 'asset', NULL),
('CI', 5, '56', 'Banques, credits de tresorerie', 'liability', NULL),
('CI', 5, '57', 'Caisse', 'asset', NULL),
('CI', 5, '571', 'Caisse siege social', 'asset', '57'),
('CI', 5, '58', 'Regies d''avances, accreditifs et virements internes', 'asset', NULL),
('CI', 5, '59', 'Depreciations de tresorerie', 'asset', NULL),

-- Classe 6 : Comptes de charges
('CI', 6, '60', 'Achats et variations de stocks', 'expense', NULL),
('CI', 6, '601', 'Achats de marchandises', 'expense', '60'),
('CI', 6, '602', 'Achats de matieres premieres', 'expense', '60'),
('CI', 6, '604', 'Achats stockes de matieres et fournitures', 'expense', '60'),
('CI', 6, '605', 'Autres achats', 'expense', '60'),
('CI', 6, '608', 'Achats d''emballages', 'expense', '60'),
('CI', 6, '61', 'Transports', 'expense', NULL),
('CI', 6, '611', 'Transports sur achats', 'expense', '61'),
('CI', 6, '612', 'Transports sur ventes', 'expense', '61'),
('CI', 6, '613', 'Transports pour le compte de tiers', 'expense', '61'),
('CI', 6, '62', 'Services exterieurs A', 'expense', NULL),
('CI', 6, '621', 'Sous-traitance generale', 'expense', '62'),
('CI', 6, '622', 'Locations et charges locatives', 'expense', '62'),
('CI', 6, '623', 'Redevances de credit-bail', 'expense', '62'),
('CI', 6, '624', 'Entretien, reparations et maintenance', 'expense', '62'),
('CI', 6, '625', 'Primes d''assurance', 'expense', '62'),
('CI', 6, '626', 'Etudes, recherches et documentation', 'expense', '62'),
('CI', 6, '63', 'Services exterieurs B', 'expense', NULL),
('CI', 6, '631', 'Frais bancaires', 'expense', '63'),
('CI', 6, '632', 'Remunerations d''intermediaires et de conseils', 'expense', '63'),
('CI', 6, '633', 'Publicite, publications, relations publiques', 'expense', '63'),
('CI', 6, '634', 'Transports du personnel', 'expense', '63'),
('CI', 6, '635', 'Deplacements, missions et receptions', 'expense', '63'),
('CI', 6, '636', 'Frais postaux et de telecommunications', 'expense', '63'),
('CI', 6, '64', 'Impots et taxes', 'expense', NULL),
('CI', 6, '641', 'Impots et taxes directs', 'expense', '64'),
('CI', 6, '645', 'Impots et taxes indirects', 'expense', '64'),
('CI', 6, '646', 'Droits d''enregistrement', 'expense', '64'),
('CI', 6, '65', 'Autres charges', 'expense', NULL),
('CI', 6, '651', 'Pertes sur creances clients', 'expense', '65'),
('CI', 6, '652', 'Quote-part de resultat sur operations faites en commun', 'expense', '65'),
('CI', 6, '66', 'Charges de personnel', 'expense', NULL),
('CI', 6, '661', 'Remunerations directes versees au personnel', 'expense', '66'),
('CI', 6, '662', 'Remunerations en nature', 'expense', '66'),
('CI', 6, '663', 'Indemnites forfaitaires', 'expense', '66'),
('CI', 6, '664', 'Charges sociales', 'expense', '66'),
('CI', 6, '668', 'Autres charges sociales', 'expense', '66'),
('CI', 6, '67', 'Frais financiers et charges assimilees', 'expense', NULL),
('CI', 6, '671', 'Interets des emprunts', 'expense', '67'),
('CI', 6, '672', 'Interets dans loyers de credit-bail', 'expense', '67'),
('CI', 6, '674', 'Pertes de change', 'expense', '67'),
('CI', 6, '676', 'Pertes sur cessions de titres de placement', 'expense', '67'),
('CI', 6, '68', 'Dotations aux amortissements et provisions', 'expense', NULL),
('CI', 6, '681', 'Dotations aux amortissements d''exploitation', 'expense', '68'),
('CI', 6, '684', 'Dotations aux provisions d''exploitation', 'expense', '68'),
('CI', 6, '687', 'Dotations aux amortissements et provisions financieres', 'expense', '68'),
('CI', 6, '69', 'Dotations HAO - Participation - Impots', 'expense', NULL),
('CI', 6, '691', 'Participation des travailleurs', 'expense', '69'),
('CI', 6, '695', 'Impot sur le resultat', 'expense', '69'),
('CI', 6, '697', 'Charges HAO', 'expense', '69'),

-- Classe 7 : Comptes de produits
('CI', 7, '70', 'Ventes', 'revenue', NULL),
('CI', 7, '701', 'Ventes de marchandises', 'revenue', '70'),
('CI', 7, '702', 'Ventes de produits finis', 'revenue', '70'),
('CI', 7, '704', 'Travaux factures', 'revenue', '70'),
('CI', 7, '705', 'Etudes facturees', 'revenue', '70'),
('CI', 7, '706', 'Services vendus', 'revenue', '70'),
('CI', 7, '707', 'Produits accessoires', 'revenue', '70'),
('CI', 7, '71', 'Subventions d''exploitation', 'revenue', NULL),
('CI', 7, '72', 'Production immobilisee', 'revenue', NULL),
('CI', 7, '73', 'Variations de stocks de produits et en-cours', 'revenue', NULL),
('CI', 7, '75', 'Autres produits', 'revenue', NULL),
('CI', 7, '754', 'Produits de cession de biens', 'revenue', '75'),
('CI', 7, '758', 'Produits divers', 'revenue', '75'),
('CI', 7, '77', 'Revenus financiers et produits assimiles', 'revenue', NULL),
('CI', 7, '771', 'Interets de prets', 'revenue', '77'),
('CI', 7, '772', 'Revenus de participations', 'revenue', '77'),
('CI', 7, '774', 'Gains de change', 'revenue', '77'),
('CI', 7, '776', 'Gains de cession de titres de placement', 'revenue', '77'),
('CI', 7, '78', 'Reprises de provisions', 'revenue', NULL),
('CI', 7, '781', 'Reprises d''amortissements', 'revenue', '78'),
('CI', 7, '784', 'Reprises de provisions d''exploitation', 'revenue', '78'),
('CI', 7, '787', 'Reprises de provisions financieres', 'revenue', '78'),
('CI', 7, '79', 'Reprises HAO - Transferts de charges', 'revenue', NULL),
('CI', 7, '791', 'Reprises de provisions HAO', 'revenue', '79'),
('CI', 7, '797', 'Produits HAO', 'revenue', '79'),
('CI', 7, '798', 'Transferts de charges', 'revenue', '79'),

-- Classe 8 : Comptes speciaux
('CI', 8, '80', 'Comptes de determination des resultats', 'special', NULL),
('CI', 8, '81', 'Valeurs comptables de cessions d''immobilisations', 'special', NULL),
('CI', 8, '82', 'Produits de cessions d''immobilisations', 'special', NULL),
('CI', 8, '83', 'Charges et produits HAO des exercices anterieurs', 'special', NULL),
('CI', 8, '84', 'Impots sur le resultat', 'special', NULL),
('CI', 8, '85', 'Dotations et reprises HAO', 'special', NULL),
('CI', 8, '86', 'Engagements hors bilan obtenus', 'special', NULL),
('CI', 8, '87', 'Engagements hors bilan accordes', 'special', NULL),
('CI', 8, '88', 'Comptes de result. en instance d''affectation', 'special', NULL)

ON CONFLICT (country_code, account_code) DO NOTHING;

-- =====================================================================
-- B. PLAN COMPTABLE SYSCOHADA — CAMEROUN (CM)
-- =====================================================================

INSERT INTO public.syscohada_chart_templates (country_code, account_class, account_code, account_name, account_type, parent_code) VALUES

-- Classe 1
('CM', 1, '10', 'Capital', 'equity', NULL),
('CM', 1, '101', 'Capital social', 'equity', '10'),
('CM', 1, '1011', 'Capital souscrit, non appele', 'equity', '101'),
('CM', 1, '1012', 'Capital souscrit, appele, non verse', 'equity', '101'),
('CM', 1, '1013', 'Capital souscrit, appele, verse', 'equity', '101'),
('CM', 1, '11', 'Reserves', 'equity', NULL),
('CM', 1, '111', 'Reserve legale', 'equity', '11'),
('CM', 1, '112', 'Reserves statutaires', 'equity', '11'),
('CM', 1, '118', 'Autres reserves', 'equity', '11'),
('CM', 1, '12', 'Report a nouveau', 'equity', NULL),
('CM', 1, '121', 'Report a nouveau crediteur', 'equity', '12'),
('CM', 1, '129', 'Report a nouveau debiteur', 'equity', '12'),
('CM', 1, '13', 'Resultat net de l''exercice', 'equity', NULL),
('CM', 1, '131', 'Resultat net : benefice', 'equity', '13'),
('CM', 1, '139', 'Resultat net : perte', 'equity', '13'),
('CM', 1, '14', 'Subventions d''investissement', 'equity', NULL),
('CM', 1, '15', 'Provisions reglementees', 'equity', NULL),
('CM', 1, '16', 'Emprunts et dettes assimilees', 'liability', NULL),
('CM', 1, '161', 'Emprunts obligataires', 'liability', '16'),
('CM', 1, '162', 'Emprunts aupres des etablissements de credit', 'liability', '16'),
('CM', 1, '17', 'Dettes de credit-bail', 'liability', NULL),
('CM', 1, '18', 'Dettes liees a des participations', 'liability', NULL),
('CM', 1, '19', 'Provisions financieres pour risques et charges', 'liability', NULL),

-- Classe 2
('CM', 2, '20', 'Charges immobilisees', 'asset', NULL),
('CM', 2, '201', 'Frais d''etablissement', 'asset', '20'),
('CM', 2, '21', 'Immobilisations incorporelles', 'asset', NULL),
('CM', 2, '211', 'Frais de recherche et de developpement', 'asset', '21'),
('CM', 2, '212', 'Brevets, licences, concessions', 'asset', '21'),
('CM', 2, '213', 'Logiciels', 'asset', '21'),
('CM', 2, '215', 'Fonds commercial', 'asset', '21'),
('CM', 2, '22', 'Terrains', 'asset', NULL),
('CM', 2, '23', 'Batiments', 'asset', NULL),
('CM', 2, '231', 'Batiments industriels', 'asset', '23'),
('CM', 2, '232', 'Batiments commerciaux', 'asset', '23'),
('CM', 2, '24', 'Materiel', 'asset', NULL),
('CM', 2, '241', 'Materiel et outillage industriel', 'asset', '24'),
('CM', 2, '244', 'Materiel et mobilier de bureau', 'asset', '24'),
('CM', 2, '245', 'Materiel de transport', 'asset', '24'),
('CM', 2, '246', 'Materiel informatique', 'asset', '24'),
('CM', 2, '26', 'Titres de participation', 'asset', NULL),
('CM', 2, '27', 'Autres immobilisations financieres', 'asset', NULL),
('CM', 2, '28', 'Amortissements', 'asset', NULL),
('CM', 2, '29', 'Provisions pour depreciation', 'asset', NULL),

-- Classe 3
('CM', 3, '31', 'Marchandises', 'asset', NULL),
('CM', 3, '32', 'Matieres premieres', 'asset', NULL),
('CM', 3, '33', 'Autres approvisionnements', 'asset', NULL),
('CM', 3, '34', 'Produits en cours', 'asset', NULL),
('CM', 3, '36', 'Produits finis', 'asset', NULL),
('CM', 3, '39', 'Depreciations des stocks', 'asset', NULL),

-- Classe 4
('CM', 4, '40', 'Fournisseurs et comptes rattaches', 'liability', NULL),
('CM', 4, '401', 'Fournisseurs', 'liability', '40'),
('CM', 4, '408', 'Fournisseurs, factures non parvenues', 'liability', '40'),
('CM', 4, '41', 'Clients et comptes rattaches', 'asset', NULL),
('CM', 4, '411', 'Clients', 'asset', '41'),
('CM', 4, '416', 'Clients douteux', 'asset', '41'),
('CM', 4, '42', 'Personnel', 'liability', NULL),
('CM', 4, '421', 'Personnel, avances et acomptes', 'asset', '42'),
('CM', 4, '422', 'Personnel, remunerations dues', 'liability', '42'),
('CM', 4, '43', 'Organismes sociaux', 'liability', NULL),
('CM', 4, '431', 'CNPS', 'liability', '43'),
('CM', 4, '44', 'Etat et collectivites publiques', 'liability', NULL),
('CM', 4, '441', 'Etat, impot sur les societes', 'liability', '44'),
('CM', 4, '443', 'Etat, TVA facturee', 'liability', '44'),
('CM', 4, '445', 'Etat, TVA recuperable', 'asset', '44'),
('CM', 4, '447', 'Etat, impots retenus a la source', 'liability', '44'),
('CM', 4, '46', 'Associes et groupe', 'liability', NULL),
('CM', 4, '47', 'Debiteurs et crediteurs divers', 'liability', NULL),
('CM', 4, '49', 'Depreciations et provisions (tiers)', 'liability', NULL),

-- Classe 5
('CM', 5, '50', 'Titres de placement', 'asset', NULL),
('CM', 5, '52', 'Banques', 'asset', NULL),
('CM', 5, '521', 'Banques locales CEMAC', 'asset', '52'),
('CM', 5, '522', 'Banques hors CEMAC', 'asset', '52'),
('CM', 5, '56', 'Banques, credits de tresorerie', 'liability', NULL),
('CM', 5, '57', 'Caisse', 'asset', NULL),
('CM', 5, '571', 'Caisse siege social', 'asset', '57'),
('CM', 5, '58', 'Virements internes', 'asset', NULL),
('CM', 5, '59', 'Depreciations de tresorerie', 'asset', NULL),

-- Classe 6
('CM', 6, '60', 'Achats et variations de stocks', 'expense', NULL),
('CM', 6, '601', 'Achats de marchandises', 'expense', '60'),
('CM', 6, '602', 'Achats de matieres premieres', 'expense', '60'),
('CM', 6, '605', 'Autres achats', 'expense', '60'),
('CM', 6, '61', 'Transports', 'expense', NULL),
('CM', 6, '62', 'Services exterieurs A', 'expense', NULL),
('CM', 6, '622', 'Locations', 'expense', '62'),
('CM', 6, '624', 'Entretien et reparations', 'expense', '62'),
('CM', 6, '625', 'Primes d''assurance', 'expense', '62'),
('CM', 6, '63', 'Services exterieurs B', 'expense', NULL),
('CM', 6, '631', 'Frais bancaires', 'expense', '63'),
('CM', 6, '632', 'Honoraires', 'expense', '63'),
('CM', 6, '633', 'Publicite', 'expense', '63'),
('CM', 6, '636', 'Telecommunications', 'expense', '63'),
('CM', 6, '64', 'Impots et taxes', 'expense', NULL),
('CM', 6, '641', 'Impots et taxes directs', 'expense', '64'),
('CM', 6, '645', 'Impots et taxes indirects', 'expense', '64'),
('CM', 6, '65', 'Autres charges', 'expense', NULL),
('CM', 6, '66', 'Charges de personnel', 'expense', NULL),
('CM', 6, '661', 'Remunerations versees au personnel', 'expense', '66'),
('CM', 6, '664', 'Charges sociales', 'expense', '66'),
('CM', 6, '67', 'Frais financiers', 'expense', NULL),
('CM', 6, '671', 'Interets des emprunts', 'expense', '67'),
('CM', 6, '674', 'Pertes de change', 'expense', '67'),
('CM', 6, '68', 'Dotations aux amortissements et provisions', 'expense', NULL),
('CM', 6, '681', 'Dotations aux amortissements d''exploitation', 'expense', '68'),
('CM', 6, '69', 'Charges HAO et impots', 'expense', NULL),
('CM', 6, '695', 'Impot sur les societes', 'expense', '69'),
('CM', 6, '697', 'Charges HAO', 'expense', '69'),

-- Classe 7
('CM', 7, '70', 'Ventes', 'revenue', NULL),
('CM', 7, '701', 'Ventes de marchandises', 'revenue', '70'),
('CM', 7, '702', 'Ventes de produits finis', 'revenue', '70'),
('CM', 7, '706', 'Services vendus', 'revenue', '70'),
('CM', 7, '707', 'Produits accessoires', 'revenue', '70'),
('CM', 7, '71', 'Subventions d''exploitation', 'revenue', NULL),
('CM', 7, '72', 'Production immobilisee', 'revenue', NULL),
('CM', 7, '73', 'Variations de stocks', 'revenue', NULL),
('CM', 7, '75', 'Autres produits', 'revenue', NULL),
('CM', 7, '77', 'Revenus financiers', 'revenue', NULL),
('CM', 7, '771', 'Interets de prets', 'revenue', '77'),
('CM', 7, '774', 'Gains de change', 'revenue', '77'),
('CM', 7, '78', 'Reprises de provisions', 'revenue', NULL),
('CM', 7, '781', 'Reprises d''amortissements', 'revenue', '78'),
('CM', 7, '79', 'Reprises HAO et transferts', 'revenue', NULL),
('CM', 7, '797', 'Produits HAO', 'revenue', '79'),

-- Classe 8
('CM', 8, '80', 'Comptes de determination des resultats', 'special', NULL),
('CM', 8, '81', 'Valeurs comptables de cessions', 'special', NULL),
('CM', 8, '82', 'Produits de cessions d''immobilisations', 'special', NULL),
('CM', 8, '84', 'Impots sur le resultat', 'special', NULL),
('CM', 8, '86', 'Engagements hors bilan obtenus', 'special', NULL),
('CM', 8, '87', 'Engagements hors bilan accordes', 'special', NULL)

ON CONFLICT (country_code, account_code) DO NOTHING;;
